/* Anordnen: Fanglinien, Raster, Ausrichten und Drehung. Alle Maße in Folienpixeln (1600 × 900), Winkel in Grad im Uhrzeigersinn. */
window.addEventListener('DOMContentLoaded',()=>{
 const E=DeckEditor,$=s=>document.querySelector(s),W=1600,H=900,ns='http://www.w3.org/2000/svg',prefsKey='vibecoding-editor-prefs',sizes=[20,25,40,50,80,100];
 const prefs={guides:true,grid:false,gridSize:50};try{const saved=JSON.parse(localStorage.getItem(prefsKey));if(saved&&typeof saved==='object'){prefs.guides=saved.guides!==false;prefs.grid=!!saved.grid;if(sizes.includes(+saved.gridSize))prefs.gridSize=+saved.gridSize}}catch{}
 const savePrefs=()=>{try{localStorage.setItem(prefsKey,JSON.stringify(prefs))}catch{}};
 const slides=$('.reveal .slides'),scale=()=>window.deck?.getScale()||1;
 const current=()=>window.deck?.getCurrentSlide()||slides.querySelector('section.present')||slides.querySelector('section');
 /* box: visible bounding box on the slide (rotated objects included). frame: the unrotated box, whose x/y stay stable while turning. */
 function box(el){const s=scale(),r=el.getBoundingClientRect(),c=(el.closest('section')||current()).getBoundingClientRect();return{left:(r.left-c.left)/s,top:(r.top-c.top)/s,width:r.width/s,height:r.height/s}}
 function frame(el){const b=box(el),w=el.offsetWidth,h=el.offsetHeight;return{...b,w,h,x:b.left+b.width/2-w/2,y:b.top+b.height/2-h/2}}
 function padding(){const cs=getComputedStyle(current());return{left:parseFloat(cs.paddingLeft)||0,right:parseFloat(cs.paddingRight)||0,top:parseFloat(cs.paddingTop)||0,bottom:parseFloat(cs.paddingBottom)||0}}
 function targets(exclude){const p=padding(),xs=[0,W/2,W],ys=[0,H/2,H];if(p.left)xs.push(p.left);if(p.right)xs.push(W-p.right);if(p.top)ys.push(p.top);if(p.bottom)ys.push(H-p.bottom);
  for(const el of current().querySelectorAll('[data-edit-id]')){if(el===exclude||el.contains(exclude)||exclude?.contains(el)||el.closest('aside')||el.style.display==='none'||!(el.offsetWidth||el.offsetHeight))continue;const b=box(el),r=n=>Math.round(n*10)/10;xs.push(r(b.left),r(b.left+b.width/2),r(b.left+b.width));ys.push(r(b.top),r(b.top+b.height/2),r(b.top+b.height))}
  const logo=window.DeckLogos?.resolve?.();if(logo){xs.push(logo.x,logo.x+logo.width/2,logo.x+logo.width);ys.push(logo.y,logo.y+logo.height/2,logo.y+logo.height)}return{xs,ys}}
 /* Guides win over the grid; the grid catches edges (not the centre) when no guide is near. Slide lines come first and keep priority unless another target is clearly (0.5 px) nearer. */
 function nearest(values,list,threshold,grid,skipCentre){let best=null;for(const v of values)for(const t of list){const d=t-v;if(Math.abs(d)<threshold&&(!best||Math.abs(d)<Math.abs(best.d)-.5))best={d,v:t,guide:true}}
  if(!best&&grid)values.forEach((v,i)=>{if(skipCentre&&i===1)return;const t=Math.round(v/grid)*grid,d=t-v;if(Math.abs(d)<threshold&&(!best||Math.abs(d)<Math.abs(best.d)))best={d,v:t,guide:false}});return best}
 function snapMove(start,dx,dy,{exclude,threshold=8}={}){const guides=[];if(!prefs.guides&&!prefs.grid)return{dx,dy,guides};const t=prefs.guides?targets(exclude):{xs:[],ys:[]},grid=prefs.grid?prefs.gridSize:0,l=start.left+dx,top=start.top+dy;
  const sx=nearest([l,l+start.width/2,l+start.width],t.xs,threshold,grid,true),sy=nearest([top,top+start.height/2,top+start.height],t.ys,threshold,grid,true);
  if(sx){dx+=sx.d;if(sx.guide)guides.push({axis:'x',v:sx.v})}if(sy){dy+=sy.d;if(sy.guide)guides.push({axis:'y',v:sy.v})}return{dx,dy,guides}}
 function snapEdge(value,{axis='x',exclude,threshold=8}={}){if(!prefs.guides&&!prefs.grid)return{d:0,guides:[]};const t=prefs.guides?targets(exclude):{xs:[],ys:[]},s=nearest([value],axis==='x'?t.xs:t.ys,threshold,prefs.grid?prefs.gridSize:0,false);return s?{d:s.d,guides:s.guide?[{axis,v:s.v}]:[]}:{d:0,guides:[]}}
 const layer=id=>{const svg=document.createElementNS(ns,'svg');svg.id=id;svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('aria-hidden','true');slides.append(svg);return svg};
 const gridLayer=layer('editor-grid'),guideLayer=layer('editor-guides');
 function line(parent,x1,y1,x2,y2,cls){const l=document.createElementNS(ns,'line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);if(cls)l.setAttribute('class',cls);parent.append(l)}
 function showGuides(list){guideLayer.replaceChildren();for(const g of list||[])g.axis==='x'?line(guideLayer,g.v,0,g.v,H):line(guideLayer,0,g.v,W,g.v)}
 function drawGrid(){gridLayer.replaceChildren();document.body.classList.toggle('grid-on',prefs.grid);if(!prefs.grid)return;const g=prefs.gridSize;for(let x=g;x<W;x+=g)line(gridLayer,x,0,x,H,x===W/2?'major':'');for(let y=g;y<H;y+=g)line(gridLayer,0,y,W,y,y===H/2?'major':'');if(W/2%g)line(gridLayer,W/2,0,W/2,H,'major');if(H/2%g)line(gridLayer,0,H/2,W,H/2,'major')}
 const icon=(lines,rects)=>`<svg viewBox="0 0 16 16" aria-hidden="true">${lines.map(([x1,y1,x2,y2])=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`).join('')}${rects.map(([x,y,w,h])=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="0.8"/>`).join('')}</svg>`;
 const icons={left:icon([[2.5,1,2.5,15]],[[4.5,3.5,9,3],[4.5,9.5,6,3]]),hcenter:icon([[8,1,8,15]],[[3,3.5,10,3],[5,9.5,6,3]]),right:icon([[13.5,1,13.5,15]],[[2.5,3.5,9,3],[5.5,9.5,6,3]]),top:icon([[1,2.5,15,2.5]],[[3.5,4.5,3,9],[9.5,4.5,3,6]]),vcenter:icon([[1,8,15,8]],[[3.5,3,3,10],[9.5,5,3,6]]),bottom:icon([[1,13.5,15,13.5]],[[3.5,2.5,3,9],[9.5,5.5,3,6]])};
 const names={left:'Linksbündig',hcenter:'Horizontal zentrieren',right:'Rechtsbündig',top:'Oben ausrichten',vcenter:'Vertikal zentrieren',bottom:'Unten ausrichten'};
 function alignButton(key,withLabel){const b=document.createElement('button');b.type='button';b.dataset.arrange=key;b.innerHTML=icons[key]+(withLabel?'<span>'+names[key]+'</span>':'');b.title=names[key]+' · am Folienrand';b.setAttribute('aria-label',names[key]);b.onclick=()=>align(key);return b}
 /* Toolbar: rotation input and quick alignment in the format row, snapping toggles in the main row. */
 const format=$('.editor-format'),del=$('#editor-delete');
 const rotateLabel=document.createElement('label');rotateLabel.className='rotate-controls';rotateLabel.innerHTML='Drehung <input id="editor-rotate" type="number" min="-180" max="180" step="1" value="0" aria-label="Drehung in Grad"><span>°</span>';
 const straight=document.createElement('button');straight.id='editor-rotate-reset';straight.type='button';straight.textContent='0°';straight.title='Drehung zurücksetzen';straight.setAttribute('aria-label','Drehung zurücksetzen');
 const group=document.createElement('span');group.className='arrange-group';group.setAttribute('role','group');group.setAttribute('aria-label','Auf der Folie ausrichten');for(const key of Object.keys(names))group.append(alignButton(key,false));
 format.insertBefore(rotateLabel,del);format.insertBefore(straight,del);format.insertBefore(group,del);
 const main=$('.editor-main'),undo=$('#editor-undo');
 const guidesButton=document.createElement('button');guidesButton.id='editor-guides-toggle';guidesButton.textContent='Fanglinien';guidesButton.title='Beim Verschieben an Folie, Rändern und anderen Objekten einrasten · Alt gedrückt halten schaltet kurz aus';
 const gridButton=document.createElement('button');gridButton.id='editor-grid-toggle';gridButton.textContent='Raster';gridButton.title='Raster anzeigen und daran einrasten';
 main.insertBefore(guidesButton,undo);main.insertBefore(gridButton,undo);
 /* Inspector tab "Objekt": exact values, alignment and snapping preferences. */
 const inspector=$('#studio-inspector'),tabs=inspector?.querySelector('.studio-tabs');let panel=null;
 if(tabs){const tabButton=document.createElement('button');tabButton.id='tab-object';tabButton.textContent='Objekt';tabButton.setAttribute('aria-pressed','false');tabs.append(tabButton);tabButton.onclick=()=>window.VibeStudio?.switchTab?.('object');
  panel=document.createElement('div');panel.id='object-properties';panel.hidden=true;panel.innerHTML=`<div class="studio-kicker">AUSGEWÄHLTES OBJEKT</div><div id="object-label"></div><div class="object-grid"><label>X<input id="object-x" type="number" step="1" aria-label="Position X"></label><label>Y<input id="object-y" type="number" step="1" aria-label="Position Y"></label><label>Breite<input id="object-width" type="number" min="80" max="1600" step="1" aria-label="Breite"></label><label>Drehung<input id="object-rotate" type="number" min="-180" max="180" step="1" aria-label="Drehung in Grad"></label></div><p class="studio-help">Folienpixel bei 1600 × 900, linke obere Ecke des ungedrehten Felds. Drehung in Grad im Uhrzeigersinn: runder Griff über dem Objekt ziehen, Umschalt rastet in 15°-Schritten, Doppelklick stellt gerade.</p><div class="studio-rule"></div><div class="studio-kicker">AUF DER FOLIE AUSRICHTEN</div><div id="object-align"></div><p class="studio-help">Richtet am Folienrand aus. Inhaltsfolien nutzen ihren inneren Rand, Kapitelfolien die Folienkante.</p><div class="studio-rule"></div><div class="studio-kicker">FANGLINIEN &amp; RASTER</div><label class="studio-checkbox"><input id="object-guides" type="checkbox"> Fanglinien beim Verschieben</label><label class="studio-checkbox"><input id="object-grid" type="checkbox"> Raster anzeigen und einrasten</label><label>Rastergröße<select id="object-grid-size" aria-label="Rastergröße">${sizes.map(s=>`<option value="${s}">${s} px</option>`).join('')}</select></label><p class="studio-help">Fanglinien greifen an Folienmitte, Rändern, anderen Texten, Bildern und dem Logo. Alt gedrückt halten schaltet Einrasten beim Ziehen vorübergehend aus. Die Einstellungen gelten für diesen Browser.</p>`;inspector.append(panel);
  const alignBox=panel.querySelector('#object-align');for(const key of Object.keys(names))alignBox.append(alignButton(key,true));}
 function selectedObject(){const el=E.selected();return el&&el.isConnected?el:null}
 function sync(){const el=selectedObject(),data=el?E.textData(el):null,on=!!el,rot=data?Number(data.rotate)||0:0;$('#editor-rotate').disabled=!on;straight.disabled=!on;group.querySelectorAll('button').forEach(b=>b.disabled=!on);if(document.activeElement!==$('#editor-rotate'))$('#editor-rotate').value=rot;
  guidesButton.setAttribute('aria-pressed',String(prefs.guides));gridButton.setAttribute('aria-pressed',String(prefs.grid));if(!panel)return;
  panel.querySelectorAll('#object-x,#object-y,#object-width,#object-rotate,#object-align button').forEach(i=>i.disabled=!on);$('#object-guides').checked=prefs.guides;$('#object-grid').checked=prefs.grid;$('#object-grid-size').value=prefs.gridSize;
  if(!on){$('#object-label').textContent='Zuerst ein Textfeld oder Bild auf der Folie anklicken.';for(const id of ['object-x','object-y','object-width','object-rotate'])$('#'+id).value='';return}
  const f=frame(el),label=el.classList.contains('user-media')?'Bild / Video':(el.textContent.replace(/\s+/g,' ').trim().slice(0,60)||'Leeres Textfeld');$('#object-label').textContent=label;
  const set=(id,value)=>{const input=$('#'+id);if(document.activeElement!==input)input.value=value};set('object-x',Math.round(f.x));set('object-y',Math.round(f.y));set('object-width',Math.round(f.w));set('object-rotate',rot)}
 function setRotation(value,commit){const el=selectedObject();if(!el||value===''||!Number.isFinite(+value))return;E.place(el,{rotate:Math.max(-180,Math.min(180,+value))});sync();if(commit)E.commit()}
 function setPosition(axis,value){const el=selectedObject();if(!el||value===''||!Number.isFinite(+value))return;const f=frame(el),data=E.textData(el),delta=+value-(axis==='x'?f.x:f.y);E.place(el,axis==='x'?{x:Math.round(((data.x||0)+delta)*10)/10}:{y:Math.round(((data.y||0)+delta)*10)/10});sync()}
 function align(key){const el=selectedObject();if(!el)return;const b=box(el),p=padding(),data=E.textData(el);let dx=0,dy=0;if(key==='left')dx=p.left-b.left;else if(key==='hcenter')dx=W/2-(b.left+b.width/2);else if(key==='right')dx=W-p.right-(b.left+b.width);else if(key==='top')dy=p.top-b.top;else if(key==='vcenter')dy=H/2-(b.top+b.height/2);else if(key==='bottom')dy=H-p.bottom-(b.top+b.height);E.place(el,{x:Math.round(((data.x||0)+dx)*10)/10,y:Math.round(((data.y||0)+dy)*10)/10});E.commit();E.status(names[key])}
 function setGuides(on){prefs.guides=!!on;savePrefs();sync();E.status(prefs.guides?'Fanglinien an · Alt gedrückt halten schaltet sie beim Ziehen aus':'Fanglinien aus')}
 function setGrid(on){prefs.grid=!!on;savePrefs();drawGrid();sync();E.status(prefs.grid?'Raster '+prefs.gridSize+' px · Objekte rasten an den Linien ein':'Raster aus')}
 $('#editor-rotate').oninput=e=>setRotation(e.target.value,false);$('#editor-rotate').onchange=()=>E.commit();straight.onclick=()=>setRotation(0,true);
 guidesButton.onclick=()=>setGuides(!prefs.guides);gridButton.onclick=()=>setGrid(!prefs.grid);
 if(panel){$('#object-rotate').oninput=e=>setRotation(e.target.value,false);$('#object-rotate').onchange=()=>E.commit();for(const axis of ['x','y']){$('#object-'+axis).oninput=e=>setPosition(axis,e.target.value);$('#object-'+axis).onchange=()=>E.commit()}$('#object-width').oninput=e=>{const v=+e.target.value;if(selectedObject()&&v>=80&&v<=1600)E.setStyle('width',v+'px')};$('#object-width').onchange=()=>E.commit();$('#object-guides').onchange=e=>setGuides(e.target.checked);$('#object-grid').onchange=e=>setGrid(e.target.checked);$('#object-grid-size').onchange=e=>{prefs.gridSize=+e.target.value;savePrefs();drawGrid();if(prefs.grid)E.status('Raster '+prefs.gridSize+' px')}}
 window.VibeArrange={box,frame,snapMove,snapEdge,showGuides,sync,selectionChanged:sync,align,prefs,redraw:drawGrid};drawGrid();sync();
});
