/* Design: Maße für Schrift und Rhythmus. Größe, Laufweite, Zeilenabstand, Schnitt und Versalien gelten Text → Feldtyp → global → Vorlage. */
window.addEventListener('DOMContentLoaded',()=>{
 const E=DeckEditor,$=s=>document.querySelector(s),F=()=>window.DeckFonts;
 const PROPS=['font-size','letter-spacing','line-height','font-weight','text-transform','font-variant'],defaults={size:100,tracking:0,leading:100,weight:'',transform:''};
 const fallbackTypes=[['title','Kapitel-Titel'],['heading','Überschriften'],['subtitle','Untertitel'],['body','Fließtext & Prompts'],['label','Beschriftungen'],['free','Freie Textfelder']];
 const types=()=>F()?.types||fallbackTypes;
 const config=()=>{const s=E.state();s.design||={global:{...defaults},types:{}};s.design.global={...defaults,...s.design.global};s.design.types||={};return s.design};
 /* Individual values live in the text's own style map; reading them must not create entries. */
 const own=el=>{const s=E.state(),id=el.dataset.editId,rec=el.matches('.user-text,.user-media')?s.added.find(t=>t.id===id):s.texts[id];return rec?.style||{}};
 const mine=new WeakMap(),bases=new WeakMap();
 function setMine(el,prop,value){let m=mine.get(el);if(!m){m={};mine.set(el,m)}if(!(prop in m))m[prop]={value:el.style.getPropertyValue(prop),priority:el.style.getPropertyPriority(prop)};el.style.setProperty(prop,value,'important')}
 function unsetMine(el,prop){const m=mine.get(el);if(!m||!(prop in m))return;const prev=m[prop];delete m[prop];if(prev.value)el.style.setProperty(prop,prev.value,prev.priority);else el.style.removeProperty(prop)}
 const blank=v=>v===undefined||v===null||v==='';
 function effective(type){const d=config(),t=d.types[type]||{},v=k=>blank(t[k])?d.global[k]:t[k];return{size:+v('size')||100,tracking:+v('tracking')||0,leading:+v('leading')||100,weight:v('weight')||'',transform:v('transform')||''}}
 function apply(){const els=[...document.querySelectorAll('.slides>section [data-edit-id]:not(.user-media)')];
  const info=els.map(el=>{const o=own(el),m=mine.get(el);for(const p of PROPS){if(o[p]){if(m)delete m[p];continue}unsetMine(el,p)}return{el,o,type:F()?.type(el)||'body'}});
  for(const i of info){const cs=getComputedStyle(i.el),size=parseFloat(cs.fontSize)||30;i.base={size,spacing:parseFloat(cs.letterSpacing)||0,leading:(cs.lineHeight==='normal'?size*1.25:parseFloat(cs.lineHeight))/size};bases.set(i.el,i.base)}
  for(const{el,o,type,base}of info){const e=effective(type),size=base.size*e.size/100,fs=o['font-size']?base.size:size;
   if(!o['font-size']&&e.size!==100)setMine(el,'font-size',size.toFixed(2)+'px');
   if(!o['letter-spacing']&&e.tracking)setMine(el,'letter-spacing',(base.spacing+e.tracking*fs).toFixed(2)+'px');
   if(!o['line-height']&&e.leading!==100)setMine(el,'line-height',(base.leading*e.leading/100).toFixed(3));
   if(!o['font-weight']&&e.weight)setMine(el,'font-weight',String(e.weight));
   if(!o['text-transform']&&e.transform){if(e.transform==='small-caps'){setMine(el,'font-variant','small-caps');setMine(el,'text-transform','none')}else setMine(el,'text-transform',e.transform)}}}
 function changed(commit){apply();E.refreshCurves();E.positionHandles();if(commit)E.commit();if(dialog.open)renderDialog();syncObject()}
 /* Dialog: one row per level, columns for the five measures, plus an example size per field type. */
 const button=document.createElement('button');button.id='editor-design';button.textContent='Design';button.setAttribute('aria-label','Design: Größen, Laufweite, Zeilenabstand');$('.editor-main').insertBefore(button,$('#editor-logo'));
 const weights=[['','Vorlage'],['300','Leicht 300'],['400','Normal 400'],['500','Medium 500'],['600','Halbfett 600'],['700','Fett 700']],transforms=[['','Vorlage'],['none','Wie geschrieben'],['uppercase','VERSALIEN'],['lowercase','kleinbuchstaben'],['small-caps','Kapitälchen']];
 const options=list=>list.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');
 const row=(key,name,global)=>`<div class="design-row${global?' design-global':''}" data-level="${key}"><div class="design-name">${name}${global?'<small>Gilt für alle Feldtypen ohne eigenen Wert</small>':''}</div><label><input data-key="size" type="number" min="40" max="250" step="5" aria-label="${name}: Größe in Prozent"><span>%</span></label><label><input data-key="tracking" type="number" min="-0.1" max="0.4" step="0.01" aria-label="${name}: Laufweite in em"><span>em</span></label><label><input data-key="leading" type="number" min="60" max="220" step="5" aria-label="${name}: Zeilenabstand in Prozent"><span>%</span></label><select data-key="weight" aria-label="${name}: Schriftschnitt">${options(weights)}</select><select data-key="transform" aria-label="${name}: Versalien">${options(transforms)}</select><div class="design-example" data-example="${key}"></div></div>`;
 const dialog=document.createElement('dialog');dialog.id='design-dialog';dialog.innerHTML=`<button class="close" aria-label="Schließen">×</button><div class="design-kicker">VIBE STUDIO / DESIGN</div><h2>Maß und Rhythmus.</h2><p class="design-intro">Alle Werte beziehen sich auf die gestaltete Vorlage: 100 % Größe und 100 % Zeilenabstand sind der Ausgangszustand, Laufweite 0 lässt die Vorlage unverändert. Leere Felder bei den Feldtypen übernehmen die globale Zeile. Einzeln formatierte Texte behalten ihre eigenen Werte; Schrift und Feldtyp eines Textes stehen unter „Schriften“.</p><div class="design-table" role="table"><div class="design-head" role="row"><div>Ebene</div><div>Größe</div><div>Laufweite</div><div>Zeilenabstand</div><div>Schnitt</div><div>Versalien</div><div>Beispiel</div></div>${row('global','Global',true)}${types().map(([id,name])=>row(id,name,false)).join('')}</div><div class="design-footer"><button id="design-reset">Alles auf Vorlage zurücksetzen</button><span class="design-note">Laufweite in em: 0,05 em sind bei 22 px etwa 1 px zusätzlicher Buchstabenabstand.</span><button id="design-done">Fertig</button></div>`;document.body.append(dialog);
 function sample(type){for(const el of document.querySelectorAll('.slides>section [data-edit-id]:not(.user-media)'))if((F()?.type(el)||'body')===type&&bases.get(el))return bases.get(el).size;return null}
 function renderDialog(){const d=config();for(const r of dialog.querySelectorAll('.design-row')){const level=r.dataset.level,global=level==='global',values=global?d.global:(d.types[level]||{}),eff=global?d.global:effective(level);
   for(const input of r.querySelectorAll('[data-key]')){const k=input.dataset.key;if(document.activeElement===input)continue;input.value=blank(values[k])?'':values[k];if(!global){if(input.tagName==='INPUT')input.placeholder=String(eff[k]);else input.title=blank(values[k])?'Übernimmt: '+(eff[k]||'Vorlage'):''}}
   const ex=r.querySelector('.design-example');if(global)ex.textContent='';else{const base=sample(level);ex.textContent=base?Math.round(base)+' → '+Math.round(base*eff.size/100)+' px':'–'}}}
 function write(level,key,raw){const d=config();const value=raw===''?'':(key==='weight'||key==='transform'?raw:Number(raw));if(level==='global'){if(value==='')d.global[key]=defaults[key];else d.global[key]=value}else{d.types[level]||={};if(value==='')delete d.types[level][key];else d.types[level][key]=value;if(!Object.keys(d.types[level]).length)delete d.types[level]}}
 dialog.addEventListener('input',e=>{const input=e.target.closest('[data-key]');if(!input||input.tagName!=='INPUT')return;const raw=input.value;if(raw!==''&&!Number.isFinite(Number(raw)))return;write(input.closest('.design-row').dataset.level,input.dataset.key,raw);changed(false)});
 dialog.addEventListener('change',e=>{const input=e.target.closest('[data-key]');if(!input)return;write(input.closest('.design-row').dataset.level,input.dataset.key,input.value);changed(true)});
 $('#design-reset').onclick=()=>{const d=config();d.global={...defaults};d.types={};changed(true)};$('#design-done').onclick=()=>dialog.close();
 button.onclick=()=>{document.activeElement?.blur();apply();renderDialog();dialog.showModal()};
 /* Objekt-Tab: individuelle Laufweite, Zeilenabstand und Versalien für den ausgewählten Text. */
 const panel=$('#object-properties');let section=null;
 if(panel){section=document.createElement('div');section.id='object-text';section.innerHTML=`<div class="studio-rule"></div><div class="studio-kicker">TEXT</div><div class="object-grid"><label>Laufweite<input id="object-tracking" type="number" min="-20" max="60" step="0.5" aria-label="Laufweite in Pixel"></label><label>Zeilenabstand<input id="object-leading" type="number" min="60" max="250" step="5" aria-label="Zeilenabstand in Prozent"></label></div><label>Versalien<select id="object-transform" aria-label="Versalien des Textes"><option value="">Vom Feldtyp übernehmen</option><option value="none">Wie geschrieben</option><option value="uppercase">VERSALIEN</option><option value="lowercase">kleinbuchstaben</option></select></label><button id="object-text-reset" class="studio-wide subtle">Laufweite &amp; Zeilenabstand vom Feldtyp übernehmen</button><p class="studio-help">Laufweite in Folienpixeln, Zeilenabstand in Prozent der Schriftgröße. Leere Felder folgen dem Feldtyp und den globalen Werten aus dem Design-Dialog.</p>`;panel.append(section);
  const selected=()=>{const el=E.selected();return el&&!el.classList.contains('user-media')?el:null};
  $('#object-tracking').oninput=e=>{const el=selected();if(!el||e.target.value===''||!Number.isFinite(+e.target.value))return;E.setStyle('letter-spacing',(+e.target.value)+'px')};$('#object-tracking').onchange=()=>E.commit();
  $('#object-leading').oninput=e=>{const el=selected(),v=+e.target.value;if(!el||e.target.value===''||!(v>=60&&v<=250))return;E.setStyle('line-height',(v/100).toFixed(3))};$('#object-leading').onchange=()=>E.commit();
  $('#object-transform').onchange=e=>{const el=selected();if(!el)return;if(e.target.value)E.setStyle('text-transform',e.target.value);else E.clearStyle('text-transform');changed(true)};
  $('#object-text-reset').onclick=()=>{const el=selected();if(!el)return;E.clearStyle('letter-spacing');E.clearStyle('line-height');changed(true)}}
 function syncObject(){if(!section)return;const el=E.selected(),on=!!el&&!el.classList.contains('user-media');section.querySelectorAll('input,select,button').forEach(i=>i.disabled=!on);if(!on){$('#object-tracking').value='';$('#object-leading').value='';$('#object-transform').value='';return}
  const o=own(el),cs=getComputedStyle(el),size=parseFloat(cs.fontSize)||30,ls=parseFloat(cs.letterSpacing)||0,lh=cs.lineHeight==='normal'?125:Math.round(parseFloat(cs.lineHeight)/size*100);
  const set=(id,value,placeholder)=>{const input=$('#'+id);if(document.activeElement===input)return;input.value=value;input.placeholder=placeholder};
  set('object-tracking',o['letter-spacing']?parseFloat(o['letter-spacing']):'',ls.toFixed(1));set('object-leading',o['line-height']?Math.round(parseFloat(o['line-height'])*100):'',String(lh));$('#object-transform').value=o['text-transform']||''}
 window.VibeDesign={apply,changed,effective,selectionChanged:syncObject,open:()=>button.onclick()};apply();syncObject();E.resetHistory();
});
