/* Local slide editor. Export starts from the pristine document, not Reveal's runtime DOM. */
window.addEventListener('DOMContentLoaded',()=>{
 const sourceHTML='<!doctype html>\n'+document.documentElement.outerHTML;
 const $=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x));
 const blank={schema:1,updatedAt:0,texts:{},added:[],logo:null,slideLogos:{},assets:[],fontFiles:[],typography:null,design:null,studio:null};
 let state;try{state={...blank,...JSON.parse($('#deck-user-data').textContent)}}catch{state=clone(blank)}
 const storageKey='vibecoding-editor-v8:'+location.pathname;
 try{const draft=JSON.parse(localStorage.getItem(storageKey));if(draft?.schema===1&&draft.updatedAt>state.updatedAt)state=draft}catch{}
 let deck,editing=false,selected=null,wasPaused=false,dirty=false,applying=false,persistTimer;
 let history=[],historyFocus=[],cursor=-1;const originals=new Map();let slides=[...document.querySelectorAll('.slides>section')];
 const selectors='.chapter-title h1,.chapter-title p,.signature,.eyebrow,h2,h3,h4,figcaption,blockquote,.setup-line,.small-label,.screen-caption span,.screen-caption small,.feedback-prompt,.closing,.endnote,.branch-diagram span,.tool-role,.tool-detail,.git-label b,.git-label span,.git-benefits p,.user-prompt,.agent-answer b,.agent-answer p,.repo-mini,.composer,.slide-copy,.story-copy';
 /* Inline elements cannot be translated or rotated; they become inline-block once, as part of their baseline style. */
 function baseStyle(el){let style=el.getAttribute('style')||'';if(getComputedStyle(el).display==='inline'){style=(style.trim()?style.trim().replace(/;?$/,';'):'')+'display:inline-block';el.setAttribute('style',style)}return style}
 slides.forEach((slide,i)=>{slide.dataset.slideId='slide-'+i;[...slide.querySelectorAll(selectors)].filter(el=>!el.closest('aside')).forEach((el,j)=>{
  const id=`s${i}-t${j}`;el.dataset.editId=id;originals.set(id,{el,html:el.innerHTML,style:baseStyle(el)});
 })});
 const toolbar=document.createElement('div');toolbar.id='editor-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Folien bearbeiten');toolbar.innerHTML=`
  <div class="editor-main"><span class="editor-brand">VIBE <b>STUDIO</b></span><button id="editor-present">Präsentieren</button><span class="editor-divider"></span><button id="editor-add" aria-label="Text hinzufügen">+ Text</button><button id="editor-logo" aria-label="Globales Logo">Logo</button><button id="editor-undo" aria-label="Rückgängig" title="Strg + Z">↶</button><button id="editor-redo" aria-label="Wiederholen" title="Strg + Umschalt + Z">↷</button><span id="editor-status" role="status">Text anklicken und direkt schreiben</span><button id="editor-save" class="primary">HTML speichern</button></div>
  <div class="editor-format"><label>Größe <input id="editor-size" type="number" min="12" max="220" step="1" aria-label="Schriftgröße"></label><label>Farbe <input id="editor-color" type="color" aria-label="Textfarbe"></label><button id="editor-bold" aria-label="Fett" title="Fett"><b>B</b></button><label>Ausrichtung <select id="editor-align" aria-label="Textausrichtung"><option value="left">Links</option><option value="center">Mitte</option><option value="right">Rechts</option><option value="justify">Blocksatz</option></select></label><label class="curve-controls">Bogen <input id="editor-curve" type="range" min="-100" max="100" step="1" value="0" aria-label="Textbogen-Stärke" title="Negativ: nach unten · Positiv: nach oben"><output id="editor-curve-value">0</output></label><button id="editor-straight" title="Bogen entfernen" aria-label="Text gerade setzen">Gerade</button><button id="editor-delete" aria-label="Textfeld löschen">Löschen</button><span class="editor-hint">Text anklicken · am Griff verschieben · rechts unten Breite ziehen · runder Griff dreht</span></div>`;
 document.body.append(toolbar);
 const move=document.createElement('button');move.id='edit-move';move.className='editor-handle';move.textContent='⠿ Verschieben';move.setAttribute('aria-label','Ausgewähltes Textfeld verschieben');move.title='Ziehen oder mit Pfeiltasten verschieben · Alt: ohne Einrasten';document.body.append(move);
 const resize=document.createElement('button');resize.id='edit-resize';resize.className='editor-handle';resize.textContent='↔';resize.setAttribute('aria-label','Textfeldbreite ändern');document.body.append(resize);
 const spin=document.createElement('button');spin.id='edit-rotate';spin.className='editor-handle';spin.textContent='⟳';spin.setAttribute('aria-label','Ausgewähltes Objekt drehen');spin.title='Ziehen zum Drehen · Umschalt: 15°-Schritte · Pfeiltasten: 1° · Doppelklick: gerade';document.body.append(spin);
 const logo=document.createElement('button');logo.id='global-logo';logo.setAttribute('aria-label','Logo dieser Folie bearbeiten');logo.innerHTML='<img alt="Präsentationslogo"><span>+ Logo</span>';$('.slides').append(logo);
 function registerSlide(slide){[...slide.querySelectorAll(selectors+', [data-edit-id]')].filter(el=>!el.closest('aside')&&!el.closest('.user-text,.user-media')).forEach((el,j)=>{const id=el.dataset.editId||(slide.dataset.slideId+'-t'+j);el.dataset.editId=id;if(!originals.has(id))originals.set(id,{el,html:el.innerHTML,style:baseStyle(el)})});slides=[...document.querySelectorAll('.slides>section')]}
 function cleanTextHTML(el){const copy=el.cloneNode(true);copy.querySelectorAll("[data-curve-runtime]").forEach(e=>e.remove());return copy.innerHTML}
 function entry(el){const id=el.dataset.editId;if(el.matches('.user-text,.user-media'))return state.added.find(x=>x.id===id);return state.texts[id]||(state.texts[id]={html:cleanTextHTML(el),x:0,y:0,style:{}})}
 function applyEntry(el,data){if(!data)return;if(typeof data.html==='string')el.innerHTML=data.html;el.dataset.x=data.x||0;el.dataset.y=data.y||0;el.style.translate=`${data.x||0}px ${data.y||0}px`;el.style.rotate=data.rotate?data.rotate+'deg':'';if(data.deleted)el.style.display='none';for(const[k,v]of Object.entries(data.style||{}))if(['font-size','color','font-weight','text-align','width','letter-spacing','line-height','text-transform'].includes(k))el.style.setProperty(k,v,'important')}
 /* Position and rotation live in slide pixels; rotation turns around the element's centre. */
 function place(el,{x,y,rotate}={}){const data=entry(el);if(!data)return;if(x!==undefined&&Number.isFinite(+x))data.x=+x;if(y!==undefined&&Number.isFinite(+y))data.y=+y;if(rotate!==undefined){const deg=Math.round((Number(rotate)||0)*10)/10;if(deg&&Math.abs(deg)<=360)data.rotate=deg;else delete data.rotate}el.dataset.x=data.x||0;el.dataset.y=data.y||0;el.style.translate=`${data.x||0}px ${data.y||0}px`;el.style.rotate=data.rotate?data.rotate+'deg':'';positionHandles()}
 function curveText(el){
  el.querySelectorAll('[data-curve-runtime]').forEach(e=>e.remove());el.classList.remove('curved-text');el.style.removeProperty('min-height');
  const data=el.matches('.user-text')?state.added.find(x=>x.id===el.dataset.editId):state.texts[el.dataset.editId],curve=Math.max(-100,Math.min(100,Number(data?.curve)||0));if(!curve||el.classList.contains('user-media')||el.style.display==='none')return;
  const text=el.textContent.replace(/\s+/g,' ').trim();if(!text)return;const cs=getComputedStyle(el),font=+parseFloat(cs.fontSize),width=el.offsetWidth||parseFloat(cs.width)||1600,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font=`${cs.fontWeight} ${cs.fontSize} ${cs.fontFamily}`;const spacing=parseFloat(cs.letterSpacing)||0,natural=Math.max(font,ctx.measureText(text).width+spacing*(text.length-1)),length=Math.min(natural,width*.91),angle=Math.max(.001,Math.abs(curve)/100*Math.PI*.83),radius=(length+font*.22)/angle,chord=2*radius*Math.sin(angle/2),sag=radius*(1-Math.cos(angle/2)),sign=Math.sign(curve),align=cs.textAlign,cx=(align==='left'||align==='start'||align==='justify')?chord/2+font*.12:(align==='right'||align==='end')?width-chord/2-font*.12:width/2,y=font*.86+sign*sag*.45;
  const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),path=document.createElementNS(ns,'path'),label=document.createElementNS(ns,'text'),textPath=document.createElementNS(ns,'textPath'),pathId='text-arc-'+el.dataset.editId;
  svg.dataset.curveRuntime='';svg.setAttribute('aria-hidden','true');svg.setAttribute('contenteditable','false');svg.setAttribute('width',width);svg.setAttribute('height',Math.max(font*1.3,el.offsetHeight));svg.setAttribute('viewBox',`0 0 ${width} ${Math.max(font*1.3,el.offsetHeight)}`);path.id=pathId;path.setAttribute('d',`M ${cx-chord/2} ${y} A ${radius} ${radius} 0 0 ${curve>0?1:0} ${cx+chord/2} ${y}`);path.setAttribute('fill','none');label.style.cssText=`fill:${cs.color};font-family:${cs.fontFamily};font-size:${font}px;font-weight:${cs.fontWeight};letter-spacing:${spacing}px`;textPath.setAttribute('href','#'+pathId);textPath.setAttribute('startOffset','50%');textPath.setAttribute('text-anchor','middle');if(length<natural){textPath.setAttribute('textLength',length);textPath.setAttribute('lengthAdjust','spacingAndGlyphs')}textPath.textContent=text;label.append(textPath);svg.append(path,label);el.append(svg);el.classList.add('curved-text');const bounds=label.getBBox(),height=Math.max(font*1.08,bounds.y+bounds.height+font*.08);el.style.minHeight=height+'px';svg.setAttribute('height',height);svg.setAttribute('viewBox',`0 0 ${width} ${height}`);
 }
 function refreshCurves(){document.querySelectorAll('.slides>section [data-edit-id]').forEach(curveText)}
 function setEditable(){document.querySelectorAll('[data-edit-id]').forEach(el=>{if(editing&&!el.classList.contains('user-media')){el.setAttribute('contenteditable','plaintext-only');el.spellcheck=true}else el.removeAttribute('contenteditable')})}
 function renderLogo(){window.DeckLogos?.render()}
 function renderAll(){applying=true;const id=selected?.dataset.editId;selected=null;window.VibeStudio?.syncSlides();slides=[...document.querySelectorAll('.slides>section')];for(const[key,o]of originals){o.el.innerHTML=o.html;o.el.setAttribute('style',o.style);o.el.dataset.x=0;o.el.dataset.y=0;applyEntry(o.el,state.texts[key])}
  document.querySelectorAll('.user-text,.user-media').forEach(e=>e.remove());for(const data of state.added){const slide=slides.find(s=>s.dataset.slideId===data.slide);if(!slide||data.deleted)continue;const el=document.createElement('div');el.className=data.kind==='media'?'user-media':'user-text';el.dataset.editId=data.id;slide.append(el);applyEntry(el,data);if(data.kind==='media'){const asset=window.VibeMedia?.get(data.assetId);if(asset){const media=document.createElement(asset.kind==='video'?'video':'img');media.src=asset.src;media.dataset.assetRef=asset.id;media.draggable=false;if(asset.kind==='video'){media.muted=true;media.loop=true;media.playsInline=true;media.className='studio-media-video'}el.append(media)}}}
  setEditable();renderLogo();window.VibeStudio?.applyProperties();window.DeckFonts?.apply();refreshCurves();applying=false;if(id)select(document.querySelector(`[data-edit-id="${CSS.escape(id)}"]`));positionHandles();
 }
 function status(text){$('#editor-status').textContent=text}
 function cacheDraft(){const bytes=(state.fontFiles||[]).reduce((n,f)=>n+(f.src?.length||0),0)+(state.assets||[]).reduce((n,a)=>n+(a.src?.length||0),0)+(state.logo?.src?.length||0)+Object.values(state.slideLogos||{}).reduce((n,l)=>n+(l.src?.length||0),0);if(bytes>2000000)throw Error('Große Medien');localStorage.setItem(storageKey,JSON.stringify(state))}
 function persist(){state.updatedAt=Date.now();dirty=true;try{cacheDraft();status('Entwurf im Browser · als HTML sichern')}catch{status('Zum Sichern bitte „HTML speichern“ nutzen')}}
 function schedulePersist(){clearTimeout(persistTimer);persistTimer=setTimeout(persist,250)}
 function comparable(){const {assets,fontFiles,updatedAt,...copy}=state;return JSON.stringify(copy)}
 function commit(){if(applying)return;const value=comparable();if(history[cursor]!==value){history.splice(cursor+1);historyFocus.splice(cursor+1);history.push(value);historyFocus.push(deck?.getCurrentSlide()?.dataset.slideId);if(history.length>60){history.shift();historyFocus.shift()}cursor=history.length-1;persist();window.VibeStudio?.changed()}$('#editor-undo').disabled=cursor<=0;$('#editor-redo').disabled=cursor>=history.length-1}
 function capture(el){if(!el||applying)return;entry(el).html=cleanTextHTML(el);schedulePersist()}
 function undo(direction){document.activeElement?.blur();const next=cursor+direction;if(next<0||next>=history.length)return;cursor=next;state={...JSON.parse(history[cursor]),assets:state.assets||[],fontFiles:state.fontFiles||[],updatedAt:Date.now()};renderAll();const focus=historyFocus[cursor];if(deck&&focus){const index=[...document.querySelectorAll('.slides>section')].findIndex(s=>s.dataset.slideId===focus);if(index>=0)deck.slide(index)}persist();window.VibeStudio?.changed();$('#editor-undo').disabled=cursor<=0;$('#editor-redo').disabled=cursor>=history.length-1}
 function rgbHex(s){const n=s.match(/[\d.]+/g);return n?'#'+n.slice(0,3).map(v=>Math.round(+v).toString(16).padStart(2,'0')).join(''):'#24231f'}
 function select(el){document.querySelectorAll('.editor-selected').forEach(e=>e.classList.remove('editor-selected'));selected=el&&el.style.display!=='none'?el:null;if(selected){selected.classList.add('editor-selected');const cs=getComputedStyle(selected),align=cs.textAlign;$('#editor-size').value=Math.round(parseFloat(cs.fontSize));$('#editor-color').value=rgbHex(cs.color);$('#editor-align').value=align==='center'?'center':(align==='right'||align==='end')?'right':align==='justify'?'justify':'left';$('#editor-bold').setAttribute('aria-pressed',Number(cs.fontWeight)>=600?'true':'false');$('#editor-curve').value=entry(selected).curve||0;$('#editor-curve-value').value=(entry(selected).curve||0)+' %'}
  for(const id of ['editor-size','editor-color','editor-align','editor-bold','editor-curve','editor-straight'])$('#'+id).disabled=!selected||selected.classList.contains('user-media');$('#editor-delete').disabled=!selected;positionHandles();window.DeckFonts?.selectionChanged();window.VibeArrange?.selectionChanged();window.VibeDesign?.selectionChanged();
 }
 /* Handles follow the rotated box: move at the bounding box, resize at the rotated bottom-right corner, rotation above the top edge. */
 function positionHandles(){if(!editing||!selected||!selected.closest('section')?.classList.contains('present')||selected.style.display==='none'){move.hidden=resize.hidden=spin.hidden=true;window.VibeArrange?.sync();return}const r=selected.getBoundingClientRect(),scale=deck?.getScale()||1,angle=(Number(entry(selected)?.rotate)||0)*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),cx=r.left+r.width/2,cy=r.top+r.height/2,w=selected.offsetWidth*scale,h=selected.offsetHeight*scale,top=toolbar.offsetHeight;move.hidden=resize.hidden=spin.hidden=false;move.style.left=Math.max(8,Math.min(innerWidth-140,r.left))+'px';move.style.top=Math.max(top+4,r.top-28)+'px';const rx=cx+(w/2)*cos-(h/2)*sin,ry=cy+(w/2)*sin+(h/2)*cos;resize.style.left=Math.min(innerWidth-28,Math.max(0,rx-11))+'px';resize.style.top=Math.min(innerHeight-32,Math.max(top,ry-11))+'px';const d=h/2+30,sx=cx+d*sin,sy=cy-d*cos;spin.style.left=Math.min(innerWidth-30,Math.max(0,sx-14))+'px';spin.style.top=Math.min(innerHeight-30,Math.max(top+2,sy-14))+'px';window.VibeArrange?.sync()}
 function toggle(force){if(!deck)return;const next=typeof force==='boolean'?force:!editing;if(next===editing)return;document.activeElement?.blur();if(next){deck.toggleOverview(false);DeckControls.stopAuto();wasPaused=DeckMotion.isPaused();DeckMotion.setPaused(true)}else{commit();DeckMotion.setPaused(wasPaused);select(null)}editing=next;document.body.classList.toggle('editing',editing);setEditable();deck.configure({keyboard:!editing,touch:!editing,transition:editing?'none':'fade'});deck.layout();positionHandles();$('#edit').setAttribute('aria-pressed',String(editing));if(editing)status('Text anklicken · Änderungen als HTML speichern');window.VibeStudio?.editingChanged(editing);renderLogo()}
 function addText(){const slide=deck.getCurrentSlide(),id='new-'+crypto.randomUUID();const data={id,slide:slide.dataset.slideId,html:'Dein Text',x:520,y:530,style:{'font-size':'36px',width:'500px',color:getComputedStyle(slide).color,'text-align':'left'}};state.added.push(data);renderAll();const el=document.querySelector(`[data-edit-id="${id}"]`);select(el);el.focus();const range=document.createRange();range.selectNodeContents(el);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);commit()}
 function addMedia(asset){const id='media-'+crypto.randomUUID();state.added.push({id,kind:'media',assetId:asset.id,slide:deck.getCurrentSlide().dataset.slideId,html:'',x:400,y:230,style:{width:'700px'}});renderAll();select(document.querySelector(`[data-edit-id="${id}"]`));commit()}
 function changeStyle(key,value){if(!selected)return;entry(selected).style[key]=value;selected.style.setProperty(key,value,'important');curveText(selected);positionHandles()}
 function clearStyle(key){if(!selected)return;delete entry(selected).style[key];selected.style.removeProperty(key);curveText(selected);positionHandles()}
 function removeText(){if(!selected)return;entry(selected).deleted=true;selected.style.display='none';select(null);commit()}
 /* Dragging moves in slide pixels. Moving snaps to guides and grid (Alt: off), resizing follows the rotated width axis, rotating turns around the centre. */
 function drag(e,kind){if(!selected||!editing)return;e.preventDefault();document.activeElement?.blur();const el=selected,rect=el.getBoundingClientRect(),scale=deck.getScale(),first=entry(el),angle=(Number(first.rotate)||0)*Math.PI/180,arrange=window.VibeArrange;const start={px:e.clientX,py:e.clientY,x:Number(el.dataset.x)||0,y:Number(el.dataset.y)||0,width:el.offsetWidth,rotate:Number(first.rotate)||0,cx:rect.left+rect.width/2,cy:rect.top+rect.height/2,box:arrange?.box(el)};start.angle=Math.atan2(e.clientY-start.cy,e.clientX-start.cx);const target=e.currentTarget;target.setPointerCapture(e.pointerId);
  const onMove=ev=>{let dx=(ev.clientX-start.px)/scale,dy=(ev.clientY-start.py)/scale;const data=entry(el),snapping=!!(arrange&&start.box&&!ev.altKey);if(kind==='move'){let guides=[];if(snapping){const s=arrange.snapMove(start.box,dx,dy,{exclude:el,threshold:8/scale});dx=s.dx;dy=s.dy;guides=s.guides}arrange?.showGuides(guides);data.x=Math.round((start.x+dx)*10)/10;data.y=Math.round((start.y+dy)*10)/10;el.dataset.x=data.x;el.dataset.y=data.y;el.style.translate=`${data.x}px ${data.y}px`}else if(kind==='rotate'){let deg=start.rotate+(Math.atan2(ev.clientY-start.cy,ev.clientX-start.cx)-start.angle)*180/Math.PI;deg=((deg+180)%360+360)%360-180;if(ev.shiftKey)deg=Math.round(deg/15)*15;else if(!ev.altKey){const near=Math.round(deg/90)*90;if(Math.abs(deg-near)<3)deg=near}deg=Math.round(deg*10)/10;if(deg===-180)deg=180;if(deg)data.rotate=deg;else delete data.rotate;el.style.rotate=deg?deg+'deg':''}else{let width=start.width+dx*Math.cos(angle)+dy*Math.sin(angle);if(snapping&&Math.abs(start.rotate)<.5){const s=arrange.snapEdge(start.box.left+width,{axis:'x',exclude:el,threshold:8/scale});width+=s.d;arrange.showGuides(s.guides)}data.style.width=Math.max(80,Math.min(1600,Math.round(width)))+'px';el.style.setProperty('width',data.style.width,'important');curveText(el)}positionHandles()};
  const end=()=>{target.removeEventListener('pointermove',onMove);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end);arrange?.showGuides([]);commit()};target.addEventListener('pointermove',onMove);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);
 }
 function exportHTML(){document.activeElement?.blur();clearTimeout(persistTimer);commit();state.updatedAt=Date.now();const doc=new DOMParser().parseFromString(sourceHTML,'text/html');doc.querySelector('#deck-user-data').textContent=JSON.stringify(state).replace(/</g,'\\u003c');const blob=new Blob(['<!doctype html>\n'+doc.documentElement.outerHTML],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Vibecoding-bearbeitet.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);dirty=false;try{cacheDraft()}catch{}status('HTML heruntergeladen · enthält Folien und Medien')}
 function openLogo(){window.DeckLogos?.open('global')}
 document.addEventListener('pointerdown',e=>{if(!editing)return;const el=e.target.closest('[data-edit-id]');if(el){select(el);return}if(e.target.closest('#editor-toolbar,.editor-handle,#global-logo,#logo-resize,dialog,.deck-ui,.studio-panel'))return;select(null)});
 document.addEventListener('input',e=>{if(e.target.matches('[data-edit-id]')){capture(e.target);positionHandles()}});
 document.addEventListener('focusout',e=>{if(e.target.matches('[data-edit-id]')&&!applying){capture(e.target);curveText(e.target);commit()}});
 document.addEventListener('paste',e=>{if(!editing||!e.target.closest('[data-edit-id]'))return;e.preventDefault();const plain=e.clipboardData.getData('text/plain');document.execCommand('insertText',false,plain)});
 document.addEventListener('keydown',e=>{const typing=e.target.closest('input,textarea,select,[contenteditable]');if(e.key.toLowerCase()==='e'&&!typing&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopImmediatePropagation();toggle();return}if(!editing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopImmediatePropagation();exportHTML();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!typing){e.preventDefault();e.stopImmediatePropagation();undo(e.shiftKey?1:-1);return}if(e.key==='Escape'&&!document.querySelector('dialog[open]')){document.activeElement?.blur();select(null)}if(!typing&&['PageDown','PageUp'].includes(e.key)){e.preventDefault();e.key==='PageDown'?deck.next():deck.prev()}},true);
 move.addEventListener('pointerdown',e=>drag(e,'move'));resize.addEventListener('pointerdown',e=>drag(e,'resize'));spin.addEventListener('pointerdown',e=>drag(e,'rotate'));
 spin.addEventListener('dblclick',()=>{if(!selected)return;place(selected,{rotate:0});commit()});
 move.addEventListener('keydown',e=>{if(!selected||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const data=entry(selected),step=e.shiftKey?10:1;data.x+=(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0);data.y+=(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0);applyEntry(selected,data);curveText(selected);positionHandles();commit()});
 spin.addEventListener('keydown',e=>{if(!selected||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?15:1,direction=(e.key==='ArrowRight'||e.key==='ArrowUp')?1:-1;let deg=(Number(entry(selected).rotate)||0)+direction*step;deg=((deg+180)%360+360)%360-180;if(deg===-180)deg=180;place(selected,{rotate:deg});commit()});
 $('#editor-present').onclick=()=>toggle(false);$('#editor-add').onclick=addText;$('#editor-undo').onclick=()=>undo(-1);$('#editor-redo').onclick=()=>undo(1);$('#editor-delete').onclick=removeText;$('#editor-save').onclick=exportHTML;$('#editor-logo').onclick=openLogo;
 $('#editor-curve').oninput=e=>{if(!selected)return;entry(selected).curve=+e.target.value;$('#editor-curve-value').value=e.target.value+' %';curveText(selected);positionHandles()};$('#editor-curve').onchange=commit;$('#editor-straight').onclick=()=>{if(!selected)return;entry(selected).curve=0;$('#editor-curve').value=0;$('#editor-curve-value').value='0 %';curveText(selected);commit()};
 $('#editor-size').oninput=e=>{const n=Number(e.target.value);if(n>=12&&n<=220)changeStyle('font-size',n+'px')};$('#editor-size').onchange=commit;
 $('#editor-color').oninput=e=>changeStyle('color',e.target.value);$('#editor-color').onchange=commit;
 $('#editor-align').onchange=e=>{changeStyle('text-align',e.target.value);commit()};$('#editor-bold').onclick=()=>{if(!selected)return;const bold=Number(getComputedStyle(selected).fontWeight)<600;changeStyle('font-weight',bold?'700':'400');$('#editor-bold').setAttribute('aria-pressed',String(bold));commit()};
 window.addEventListener('resize',()=>requestAnimationFrame(positionHandles));window.addEventListener('beforeunload',e=>{clearTimeout(persistTimer);if(dirty){try{cacheDraft()}catch{}}});
 document.fonts.ready.then(refreshCurves);renderAll();history=[comparable()];cursor=0;select(null);$('#editor-undo').disabled=$('#editor-redo').disabled=true;
 window.DeckEditor={selected:()=>selected,textData:entry,toggle,isEditing:()=>editing,state:()=>state,registerSlide,refresh:renderAll,commit,persist,status,addMedia,select,positionHandles,refreshCurves,place,setStyle:changeStyle,clearStyle,resetHistory(){history=[comparable()];historyFocus=[deck?.getCurrentSlide()?.dataset.slideId];cursor=0;$('#editor-undo').disabled=$('#editor-redo').disabled=true},setLogo(asset){window.DeckLogos?.setAsset(asset,'global')},connect(d){deck=d;window.VibeStudio?.connect(deck);deck.on('slidechanged',()=>{document.activeElement?.blur();refreshCurves();select(null);renderLogo()});renderLogo();deck.on('resize',()=>{refreshCurves();positionHandles()})}};
});
