/* Animated vector figures for the content slides. Static line art is inline SVG; every moving part is an HTML element animated with transform/opacity only (figures.css), so the compositor drives it. Figures are inserted at load and are idempotent: a slide that already carries its figure (duplicate, stored HTML) is left alone. */
window.addEventListener('DOMContentLoaded',()=>{
 const F1=`<svg viewBox="0 0 1420 150" width="1420" height="150"><path class="f1-main in" d="M60 100H1360"/><path class="f1-branch in" d="M430 100C500 100 520 40 600 40H900C980 40 1000 100 1070 100"/><g class="f1-spark"><circle cx="60" cy="100" r="5"/><path d="M60 82v-10M60 118v10M42 100H32M78 100h10M47 87l-7-7M73 87l7-7M47 113l-7 7M73 113l7 7"/></g><g class="f1-nodes"><circle class="f1-node m" style="--d:0s" cx="200" cy="100" r="7"/><circle class="f1-node m" style="--d:1.3s" cx="340" cy="100" r="7"/><circle class="f1-node fork m" style="--d:2.6s" cx="430" cy="100" r="8"/><circle class="f1-node br m" style="--d:3.9s" cx="650" cy="40" r="6"/><circle class="f1-node m" style="--d:5.2s" cx="760" cy="100" r="7"/><circle class="f1-node br m" style="--d:6.5s" cx="800" cy="40" r="6"/><circle class="f1-node fork m" style="--d:7.8s" cx="1070" cy="100" r="8"/><circle class="f1-node m" style="--d:9.1s" cx="1220" cy="100" r="7"/></g><g class="f1-review"><circle cx="1150" cy="58" r="14"/><path d="M1143 58l5 5 9-10"/></g><text class="f1-label" x="1300" y="88">main</text><text class="f1-label branch" x="750" y="26" text-anchor="middle">branch</text><text class="f1-label review" x="1150" y="34" text-anchor="middle">review</text></svg><i class="f1-dot m" style="--d:0s"></i><i class="f1-dot m" style="--d:3s"></i><i class="f1-dot m" style="--d:6s"></i><i class="f1-branch-dot m"></i>`;
 const F3='<i class="f3-hand m"></i><i class="f3-flash m"></i>';
 const F5='<i class="f5-pulse m" style="--d:0s"></i><i class="f5-pulse m" style="--d:4s"></i><i class="f5-sat m" style="--r:250px;--t:26s;--a:20deg;--s:12px;--c:#e6d3b8"></i><i class="f5-sat m" style="--r:284px;--t:38s;--a:200deg;--s:9px;--c:#c79e74;--dir:reverse"></i><i class="f5-sat m" style="--r:250px;--t:26s;--a:190deg;--s:8px;--c:#9fb3a2"></i>';
 const F7=`<svg viewBox="0 0 360 84" width="360" height="84"><path class="f7-back" d="M330 30C330 -12 30 -12 30 30"/><path class="f7-line" d="M30 30H330"/><circle class="f7-node m" style="--d:0s" cx="30" cy="30" r="9"/><circle class="f7-node m" style="--d:1.8s" cx="180" cy="30" r="9"/><circle class="f7-node m" style="--d:3.6s" cx="330" cy="30" r="9"/><text x="30" y="66" text-anchor="middle">beschreiben</text><text x="180" y="66" text-anchor="middle">ausprobieren</text><text x="330" y="66" text-anchor="middle">freigeben</text></svg><i class="f7-dot m"></i>`;
 const F9a='<svg viewBox="0 0 170 64" width="170" height="64"><path class="f9-line" d="M12 32H148"/><path class="f9-head" d="M138 22l12 10-12 10"/></svg><i class="f9-pkt m" style="--d:0s"></i><i class="f9-pkt m" style="--d:1.6s"></i>';
 const F9b='<svg viewBox="0 0 170 64" width="170" height="64"><path class="f9-line" d="M12 32H158"/><path class="f9-head" d="M148 22l10 10-10 10"/><path class="f9-head" d="M22 22l-10 10 10 10"/></svg><i class="f9-dot to m"></i><i class="f9-dot back m"></i>';
 const esc=t=>String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;');
 const F11=s=>{const [a,b]=(s.dataset.figBlocks||'Container|Datenbank').split('|'),slab=s.dataset.figSlab||'GitLab · gemeinsame Grundlage';return `<i class="f11-block a">${esc(a)}</i><i class="f11-block b">${esc(b)}</i><i class="f11-slab">${esc(slab)}</i><i class="f11-pole"></i><i class="f11-flag"></i><i class="f11-ring" style="--d:0s"></i><i class="f11-ring" style="--d:1.2s"></i>`};
 /* Fünf Stationen als Runde für „So arbeitet ein Agent“; Beschriftungen aus data-fig-stations (durch | getrennt). */
 const F10=s=>{const names=(s.dataset.figStations||'Auftrag|Kontext|Änderung|Prüfung|Merge').split('|').slice(0,8),n=names.length,span=Math.min(1420,Number(s.dataset.figSpan)||1340),x0=Math.round((1420-span)/2),x1=x0+span,cy=Math.round(40-(Number(s.dataset.figArc)||40)/.75),xs=names.map((_,i)=>n>1?Math.round(x0+i*span/(n-1)):710),back=`M${x1} 40C${x1} ${cy} ${x0} ${cy} ${x0} 40`,path=`M${x0} 40H${x1}C${x1} ${cy} ${x0} ${cy} ${x0} 40`,cycle=12,share=span/(span*2.045);return `<svg viewBox="0 0 1420 104" width="1420" height="104"><path class="f7-back" d="${back}"/><path class="f7-line f10-line" d="M${x0} 40H${x1}"/>${xs.map((x,i)=>`<circle class="f7-node m" style="--d:${(n>1?cycle*share*i/(n-1):0).toFixed(2)}s" cx="${x}" cy="40" r="9"/>`).join('')}${xs.map((x,i)=>`<text x="${x}" y="80" text-anchor="middle">${esc(names[i]||'')}</text>`).join('')}</svg><i class="f7-dot f10-dot m" style="offset-path:path('${path}')"></i>`};
 /* Nächstes-Wort-Animation: Satzanfang aus data-fig-sentence (Wörter mit |), Kandidaten aus data-fig-candidates (Wort:Prozent mit |); der erste Kandidat gewinnt. */
 const F12=s=>{const words=(s.dataset.figSentence||'Git|ist|ein|Ordner|mit').split('|'),cands=(s.dataset.figCandidates||'Gedächtnis:71|Geschichte:18|Gefühl:3').split('|').map(c=>c.split(':'));return `<i class="tk-line">${words.map((w,i)=>`<i class="tk m" style="--i:${i}">${esc(w)}</i>`).join('')}<i class="tk pick m">${esc(cands[0][0])}</i><i class="tk caret m"></i></i><i class="tk-cands m">${cands.map((c,i)=>`<i class="tk-cand m" style="--i:${i};--p:${Number(c[1])||0}"><i class="tk-word">${esc(c[0])}</i><i class="tk-bar"><i></i></i><i class="tk-pct">${esc(c[1])} %</i></i>`).join('')}</i>`};
 /* Zeitleiste: data-fig-years = Jahr|Beschriftung|Jahr|Beschriftung … */
 const F13=s=>{const parts=(s.dataset.figYears||'2005|Git|2008|GitHub|2022|ChatGPT|2025|Vibe Coding').split('|'),items=[];for(let i=0;i+1<parts.length;i+=2)items.push({year:parts[i],label:parts[i+1]});const n=items.length,pos=i=>n>1?40+i*1340/(n-1):710,edge=i=>i===0&&n>1?' first':i===n-1&&n>1?' last':'';return `<svg viewBox="0 0 1420 160" width="1420" height="160"><path class="tl-line" d="M40 60H1380"/>${items.map((it,i)=>`<circle class="tl-node m${it.year||it.label?'':' minor'}" style="--i:${i};--d:${(n>1?5.3*i/(n-1):0).toFixed(2)}s" cx="${pos(i)}" cy="60" r="${it.year||it.label?8:5}"/>`).join('')}</svg>${items.map((it,i)=>(it.year?`<i class="tl-year m${edge(i)}" style="--i:${i};left:${pos(i)}px">${esc(it.year)}</i>`:'')+(it.label?`<i class="tl-label m${edge(i)}" style="--i:${i};left:${pos(i)}px">${esc(it.label)}</i>`:'')).join('')}<i class="tl-run m"></i>`};
 /* Runden: data-fig-rounds = Beschriftung je Runde (mit |), Balken wachsen von links nach rechts. */
 const F14=s=>{const names=(s.dataset.figRounds||'Runde 1|Runde 2|Runde 3|Runde 4|Runde 5').split('|').slice(0,6),n=names.length,w=Math.min(220,Math.floor(1300/n)-30);return names.map((nm,i)=>`<i class="rb m" style="--i:${i};--h:${60+Math.round(160*i/Math.max(1,n-1))}px;--w:${w}px;left:${Math.round(60+i*(1300/n))}px"><i class="rb-bar"><i class="rb-dot m" style="--i:${i}"></i></i><i class="rb-num">${i+1}</i><i class="rb-label">${esc(nm)}</i></i>`).join('')};
 /* Der Chat ist weg: Ein Chatfenster, dessen Verlauf sich auflöst und neu getippt wird. */
 const F15=()=>{const w=[420,300,520,260,460];return `<i class="ch-win m"><i class="ch-bar"><i></i><i></i><i></i></i>${w.map((x,i)=>`<i class="ch-b ${i%2?'r':'l'} m" style="--i:${i};--w:${x}px"></i>`).join('')}</i><i class="ch-x m">×</i>`};
 /* Pull-Request-Reihe: data-fig-prs Prüfhaken auf einer Linie, ein Punkt läuft darüber. */
 const F16=s=>{const n=Math.min(30,Math.max(3,Number(s.dataset.figPrs)||16)),gap=1420/n;return `<svg viewBox="0 0 1420 60" width="1420" height="60"><path class="pr-line" d="M${(gap/2).toFixed(1)} 30H${(1420-gap/2).toFixed(1)}"/></svg>${[...Array(n)].map((_,i)=>`<i class="pr m" style="--i:${i};--n:${n};left:${Math.round(gap/2+i*gap-22)}px"><svg viewBox="0 0 24 24" width="24" height="24"><path d="M6 12l4 4 8-9"/></svg></i>`).join('')}<i class="pr-run m"></i>`};
 /* Filmstreifen: zwölf Bilder mit Codezeilen, laufen endlos nach links (zwei Kopien, Versatz um eine Breite). */
 const F17=()=>{const widths=[70,50,80,40,64,56,76,44,60,52,72,48],frames=[...Array(12)].map((_,i)=>`<i class="fm-frame">${[...Array(4)].map((_,k)=>`<i class="fm-line" style="--w:${widths[(i*4+k)%12]}%"></i>`).join('')}</i>`).join('');return `<i class="fm-strip m"><i class="fm-holes t"></i><i class="fm-holes b"></i>${frames}${frames}</i>`};
 /* Zwei Linien treffen sich: unten Versionierung, oben Sprachmodelle, ab dem Treffpunkt eine gemeinsame Linie. Beschriftungen aus data-fig-lower, data-fig-upper (Jahr|Name|…), data-fig-meet, data-fig-end, data-fig-names. */
 const F18=s=>{const pairs=v=>{const p=(v||'').split('|'),o=[];for(let i=0;i+1<p.length;i+=2)o.push([p[i],p[i+1]]);return o},lower=pairs(s.dataset.figLower||'2005|Git|2008|GitHub'),upper=pairs(s.dataset.figUpper||'2017|Transformer|2022|ChatGPT'),meet=s.dataset.figMeet||'2025',end=s.dataset.figEnd||'',names=(s.dataset.figNames||'|').split('|');
  const LP='M40 236H700C860 236 880 150 1040 150',UP='M480 64H700C860 64 880 150 1040 150',MP='M1040 150H1380',lx=[40,300],ux=[480,700];
  const node=(x,y,c,i,big)=>`<circle class="cv-node ${c} m" style="--i:${i}" cx="${x}" cy="${y}" r="${big?11:8}"/>`;
  const lab=(x,y,t,c,a='middle')=>`<text class="${c}" x="${x}" y="${y}" text-anchor="${a}">${esc(t)}</text>`;
  return `<svg viewBox="0 0 1420 300" width="1420" height="300"><path class="cv-line lower" d="${LP}"/><path class="cv-line upper" d="${UP}"/><path class="cv-line merged" d="${MP}"/>${lower.map((it,i)=>node(lx[i]??lx[0],236,'lower',i)).join('')}${upper.map((it,i)=>node(ux[i]??ux[0],64,'upper',i+2)).join('')}${node(1040,150,'meet',4,true)}${node(1380,150,'end',5)}<g class="cv-labels">${lower.map((it,i)=>lab((lx[i]??lx[0])-(i?0:9),282,it[0],'cv-year',i?'middle':'start')+lab((lx[i]??lx[0])-(i?0:9),314,it[1],'cv-name',i?'middle':'start')).join('')}${upper.map((it,i)=>lab(ux[i]??ux[0],2,it[0],'cv-year')+lab(ux[i]??ux[0],34,it[1],'cv-name')).join('')}${lab(1066,126,meet,'cv-meet','start')}${end?lab(1392,196,end,'cv-end','end'):''}${names[0]?lab(60,220,names[0],'cv-tag','start'):''}${names[1]?lab(456,72,names[1],'cv-tag','end'):''}</g></svg><i class="cv-dot lower m" style="offset-path:path('${LP}')"></i><i class="cv-dot upper m" style="offset-path:path('${UP}')"></i><i class="cv-dot merged m" style="offset-path:path('${MP}')"></i><i class="cv-ring m"></i>`};
 /* Schnurren: Wellenform aus data-fig-bars Balken (Standard 64) mit zwei Schüben wie Ein- und Ausatmen; die Balken flattern versetzt, so läuft eine Welle durch. */
 const F19=s=>{const n=Math.min(96,Math.max(16,Number(s.dataset.figBars)||64)),gap=1420/n;return '<i class="pw-axis"></i>'+[...Array(n)].map((_,i)=>{const e=Math.sin(Math.PI*((2*i/(n-1))%1)),h=Math.round(150*(.08+.92*e*(.5+.5*Math.abs(Math.sin(i*1.7)))));return `<i class="pw m" style="--i:${i};left:${Math.round(gap/2+i*gap-3)}px;top:${(150-h)/2}px;height:${h}px"></i>`}).join('')};
 /* Kontextfenster: Nachrichten füllen das Fenster; ist es voll, verdichtet die KI sie zur Zusammenfassung. Das Repo daneben behält Code, README und Notizen: Danach liest die KI dort neu ein, Ergebnisse werden dort festgehalten. Beschriftungen aus data-fig-labels (9 Einträge mit |). */
 const F20=s=>{const L=(s.dataset.figLabels||'kontextfenster|zusammenfassung|repo|Code|README|Notizen|versionen|festhalten|neu einlesen').split('|'),w=[420,300,470,260,380];return `<svg class="cc-arrows" viewBox="0 0 1420 300" width="1420" height="300"><path d="M660 104H798M788 95l10 9-10 9"/><path d="M798 206H660M670 197l-10 9 10 9"/></svg><i class="cc-win"><i class="cc-title">${esc(L[0])}</i><i class="cc-gauge"><i class="cc-fill m"></i></i><i class="cc-limit m"></i><i class="cc-sum m">${esc(L[1])}</i>${w.map((x,i)=>`<i class="cc-msg ${i%2?'r':'l'} c${i+1} m" style="width:${x}px;top:${118+i*34}px"></i>`).join('')}</i><i class="cc-label out">${esc(L[7])}</i><i class="cc-label in">${esc(L[8])}</i><i class="cc-dot out m"></i><i class="cc-dot in m"></i><i class="cc-repo"><i class="cc-title">${esc(L[2])}</i>${[3,4,5].map((k,i)=>`<i class="cc-file f${i+1}" style="top:${60+i*48}px"><i class="cc-hl m"></i><i class="cc-ico"></i>${esc(L[k])}</i>`).join('')}<i class="cc-vlabel">${esc(L[6])}</i><i class="cc-line"></i>${[0,1,2,3,4,5].map(i=>`<i class="cc-ver" style="left:${40+i*96}px"></i>`).join('')}<i class="cc-save m"></i></i>`};
 const fig=(cls,style,markup)=>`<div class="fig ${cls}" aria-hidden="true" style="${style}">${markup}</div>`;
 const once=(node,cls,style,markup,where='beforeend')=>{if(!node.querySelector('.'+cls))node.insertAdjacentHTML(where,fig(cls,style,markup))};
 const build={
  'tools-intro':s=>once(s,'fig-commits',`left:90px;top:${s.dataset.figTop||668}px;width:1420px;height:150px`,F1),
  'git-basics-slide':s=>once(s,'fig-commits',`left:90px;top:${s.dataset.figTop||596}px;width:1420px;height:150px`,F1),
  'agent-loop-slide':s=>once(s,'fig-round fig-loop5',`left:90px;top:${s.dataset.figTop||700}px;width:1420px;height:104px`,F10(s)),
  'context-slide':s=>once(s,'fig-context','left:0;top:0;width:1600px;height:900px',F3),
  'freedom-slide':s=>{const orbit=s.querySelector('.repo-orbit');if(orbit)once(orbit,'fig-orbit','left:0;top:0;width:100%;height:100%',F5,'afterbegin')},
  'workflow-slide':s=>once(s,'fig-round','left:1150px;top:96px;width:360px;height:84px',F7),
  'runtime-slide':s=>s.querySelectorAll('.runtime-link i').forEach((el,i)=>{if(!el.querySelector('svg')){el.innerHTML=i?F9b:F9a;el.classList.add('fig-link')}}),
  'decision-slide':s=>once(s,'fig-foundation',`left:90px;top:${s.dataset.figTop||712}px;width:1420px;height:114px`,F11(s)),
  'tokens-slide':s=>once(s,'fig-tokens',`left:90px;top:${s.dataset.figTop||420}px;width:1420px;height:360px`,F12(s)),
  'timeline-slide':s=>once(s,'fig-timeline',`left:90px;top:${s.dataset.figTop||520}px;width:1420px;height:160px`,F13(s)),
  'rounds-slide':s=>once(s,'fig-rounds',`left:90px;top:${s.dataset.figTop||420}px;width:1420px;height:360px`,F14(s)),
  'statement-slide':s=>{const loop=s.dataset.figStations;if(loop)once(s,'fig-round fig-loop5',`left:90px;top:${s.dataset.figTop||640}px;width:1420px;height:104px`,F10(s))},
  'chat-slide':s=>once(s,'fig-chat',`left:90px;top:${s.dataset.figTop||440}px;width:1420px;height:340px`,F15()),
  'prs-slide':s=>once(s,'fig-prs',`left:90px;top:${s.dataset.figTop||560}px;width:1420px;height:60px`,F16(s)),
  'film-slide':s=>once(s,'fig-film',`left:90px;top:${s.dataset.figTop||540}px;width:1420px;height:150px`,F17()),
  'converge-slide':s=>once(s,'fig-converge',`left:90px;top:${s.dataset.figTop||420}px;width:1420px;height:300px`,F18(s)),
  'purr-slide':s=>once(s,'fig-purr',`left:90px;top:${s.dataset.figTop||560}px;width:1420px;height:150px`,F19(s)),
  'compact-slide':s=>once(s,'fig-compact',`left:90px;top:${s.dataset.figTop||440}px;width:1420px;height:300px`,F20(s))
 };
 function apply(root=document){root.querySelectorAll('.slides>section').forEach(s=>{for(const [cls,make] of Object.entries(build))if(s.classList.contains(cls))make(s)})}
 apply();
 /* Zahlen mit data-count zählen beim Erscheinen der Folie hoch (nicht im Editor, nicht bei reduzierter Bewegung). */
 const counted=new WeakSet(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function countUp(el){const target=Number(el.dataset.count);if(!Number.isFinite(target))return;if(reduced.matches||document.body.classList.contains('editing')){el.textContent=String(target);return}const start=performance.now(),ms=Number(el.dataset.countMs)||1400;const step=now=>{const t=Math.min(1,(now-start)/ms),v=Math.round(target*(1-Math.pow(1-t,3)));el.textContent=String(v);if(t<1)requestAnimationFrame(step)};requestAnimationFrame(step)}
 new MutationObserver(list=>{for(const m of list){const el=m.target;if(!(el instanceof Element)||!el.matches('section.present'))continue;if(counted.has(el))continue;counted.add(el);el.querySelectorAll('[data-count]').forEach(countUp);setTimeout(()=>counted.delete(el),2000)}}).observe(document.querySelector('.reveal .slides')||document.body,{attributes:true,attributeFilter:['class'],subtree:true});
 window.VibeFigures={apply,countUp};
});
