/* Font files are embedded resources; assignments follow text → field type → global. */
window.addEventListener('DOMContentLoaded',()=>{
 const E=DeckEditor,$=s=>document.querySelector(s);
 const builtins=[{id:'dm-sans',name:'DM Sans',family:'"DM Sans", Arial, sans-serif',detail:'Aktuelle Schrift · eingebettet'},{id:'sans',name:'Arial / Sans Serif',family:'Arial, Helvetica, sans-serif',detail:'Systemschrift'},{id:'serif',name:'Georgia / Serif',family:'Georgia, "Times New Roman", serif',detail:'Systemschrift'},{id:'mono',name:'Courier / Monospace',family:'"Courier New", Courier, monospace',detail:'Systemschrift'}];
 const types=[['title','Kapitel-Titel'],['heading','Überschriften'],['subtitle','Untertitel'],['body','Fließtext & Prompts'],['label','Beschriftungen'],['free','Freie Textfelder']];
 const state=()=>E.state(),files=()=>state().fontFiles||=[],config=()=>state().typography||={global:'dm-sans',types:{}};
 const familyName=f=>'VibeFont_'+f.id.replace(/[^a-z0-9]/gi,'_');
 const catalog=()=>[...builtins,...files().map(f=>({...f,family:'"'+familyName(f)+'", "DM Sans", sans-serif',detail:f.format.toUpperCase()+' · '+Math.ceil(f.size/1024)+' KB · eingebettet'}))];
 const find=id=>catalog().find(f=>f.id===id)||builtins[0];
 function record(el){if(!el)return {};return el.classList.contains('user-text')?state().added.find(t=>t.id===el.dataset.editId)||{}:state().texts[el.dataset.editId]||{}}
 function type(el){const explicit=record(el).fontType;if(types.some(([id])=>id===explicit))return explicit;if(el.matches('.user-text'))return 'free';if(el.matches('h1'))return 'title';if(el.matches('h2,h3,h4,.git-label b'))return 'heading';if(el.matches('.chapter-title p,.tool-role'))return 'subtitle';if(el.matches('.eyebrow,.signature,figcaption,.small-label,.screen-caption span,.screen-caption small,.endnote,.branch-diagram span,.repo-mini,.composer'))return 'label';return 'body'}
 function effective(el){return record(el).fontId||config().types[type(el)]||config().global||'dm-sans'}
 let pending=0,previewId='dm-sans',busy=false;const loaded=new Map();
 function sync(){for(const file of files()){if(loaded.has(file.id))continue;pending++;const task=(async()=>{if(!file.src.startsWith('data:'))throw Error('Keine eingebettete Schriftdatei');const face=new FontFace(familyName(file),'url("'+file.src+'")');await face.load();document.fonts.add(face);return face})();loaded.set(file.id,task);task.catch(()=>{message('Die Schrift „'+file.name+'“ konnte nicht geladen werden. DM Sans dient als Ersatz.');}).finally(()=>{pending--;apply();E.refreshCurves();E.positionHandles();window.VibeStudio?.changed()})}}
 function apply(){sync();const global=find(config().global).family;for(const el of document.querySelectorAll('.slides,.studio-thumb')){el.style.fontFamily=global;el.style.setProperty('--sans',global)}for(const el of document.querySelectorAll('.slides>section [data-edit-id]:not(.user-media)')){el.dataset.fontType=type(el);el.style.setProperty('font-family',find(effective(el)).family,'important')}selectionChanged();if(dialog.open)renderAssignments()}
 function changed(){apply();E.refreshCurves();E.positionHandles();E.commit();renderCatalog()}
 const manage=document.createElement('button');manage.id='editor-fonts';manage.textContent='Schriften';manage.setAttribute('aria-label','Schriften verwalten');$('.editor-main').insertBefore(manage,$('#editor-logo'));
 const quick=document.createElement('label');quick.className='font-quick';quick.innerHTML='Schrift <select id="editor-font" aria-label="Schrift des Textfelds"></select>';$('.editor-format').prepend(quick);
 const dialog=document.createElement('dialog');dialog.id='fonts-dialog';dialog.innerHTML=`<button class="close" aria-label="Schließen">×</button><div class="font-kicker">VIBE STUDIO / TYPOGRAFIE</div><h2>Deine Schrift. Dein Ton.</h2><p class="font-intro">Einzeltext vor Feldtyp vor globaler Schrift. DM Sans bleibt jederzeit verfügbar.</p><div class="font-layout"><div class="font-assignments"><div class="font-group-title">GLOBAL</div><label class="font-row">Standardschrift<select id="font-global" aria-label="Globale Schrift"></select></label><div class="font-group-title">JE FELDTYP</div><div id="font-types"></div><div class="font-group-title">AUSGEWÄHLTER TEXT</div><div id="font-current-label"></div><label class="font-row">Feldtyp<select id="font-current-type" aria-label="Feldtyp des Textes"></select></label><label class="font-row">Schrift<select id="font-current" aria-label="Individuelle Schrift"></select></label><div id="font-inheritance"></div></div><div class="font-library"><div class="font-group-title">SCHRIFTEN & VORSCHAU</div><div id="font-sample" aria-label="Schriftvorschau">aus ideen<br>wird etwas.<small>Ää Öö Üü ß · 0123456789</small></div><div id="font-sample-name"></div><div id="font-list"></div><label class="font-upload">+ Eigene Schriften hochladen<input id="font-files" type="file" accept=".woff,.woff2,.ttf,.otf,font/woff,font/woff2,font/ttf,font/otf" multiple></label><div id="font-drop">WOFF · WOFF2 · TTF · OTF<br>Dateien hierher ziehen · bis 15 MB je Datei</div><p id="font-message" role="status">Hochgeladene Schriften werden in der HTML gespeichert und sind auch offline verfügbar.</p></div></div><div class="font-footer"><span>Systemschriften können auf anderen Geräten leicht abweichen.</span><button id="font-done">Fertig</button></div>`;document.body.append(dialog);
 for(const[id,name]of types){const label=document.createElement('label');label.className='font-row';label.textContent=name;const select=document.createElement('select');select.id='font-type-'+id;select.setAttribute('aria-label','Schrift für '+name);label.append(select);$('#font-types').append(label);select.onchange=()=>{if(select.value)config().types[id]=select.value;else delete config().types[id];changed()};const option=document.createElement('option');option.value=id;option.textContent=name;$('#font-current-type').append(option)}
 function options(select,value,inherit){const signature=catalog().map(f=>f.id+f.name).join('|')+'|'+(inherit||'');if(select.dataset.options!==signature){select.replaceChildren();if(inherit){const option=document.createElement('option');option.value='';option.textContent=inherit;select.append(option)}for(const f of catalog()){const option=document.createElement('option');option.value=f.id;option.textContent=f.name;select.append(option)}select.dataset.options=signature}select.value=value||''}
 function selected(){const el=E.selected();return el&&!el.classList.contains('user-media')?el:null}
 function selectionChanged(){const el=selected(),select=$('#editor-font');select.disabled=!el;options(select,record(el).fontId,'Vom Feldtyp übernehmen');select.title=el?'Aktuell: '+find(effective(el)).name:'Zuerst einen Text auswählen';if(dialog.open)renderAssignments()}
 function renderAssignments(){options($('#font-global'),config().global);for(const[id]of types)options($('#font-type-'+id),config().types[id],'Global übernehmen');const el=selected(),plain=el?.cloneNode(true);plain?.querySelectorAll('[data-curve-runtime]').forEach(e=>e.remove());$('#font-current').disabled=$('#font-current-type').disabled=!el;$('#font-current-label').textContent=el?(plain.textContent.trim().replace(/\s+/g,' ').slice(0,65)||'Leeres Textfeld'):'Wähle auf der Folie zuerst einen Text aus.';$('#font-current-type').value=el?type(el):'body';options($('#font-current'),record(el).fontId,'Vom Feldtyp übernehmen');$('#font-inheritance').textContent=el?'Verwendet: '+find(effective(el)).name+' · '+(record(el).fontId?'individuell':config().types[type(el)]?'aus dem Feldtyp':'global'):''}
 function renderCatalog(){const list=$('#font-list');list.replaceChildren();for(const f of catalog()){const row=document.createElement('button');row.className='font-card';row.setAttribute('aria-pressed',String(f.id===previewId));row.dataset.fontId=f.id;const name=document.createElement('b');name.textContent=f.name;name.style.fontFamily=f.family;const note=document.createElement('span');note.textContent=f.detail;row.append(name,note);row.onclick=()=>{previewId=f.id;renderCatalog()};list.append(row)}$('#font-sample').style.fontFamily=find(previewId).family;$('#font-sample-name').textContent=find(previewId).name}
 function open(){document.activeElement?.blur();previewId=selected()?effective(selected()):config().global;renderAssignments();renderCatalog();dialog.showModal()}
 function setIndividual(value){const el=selected();if(!el)return;const data=E.textData(el);if(value)data.fontId=value;else delete data.fontId;changed()}
 function message(text){$('#font-message').textContent=text}
 const toDataURL=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Datei nicht lesbar.'));reader.readAsDataURL(file)});
 async function importFont(file){const ext=file.name.split('.').pop().toLowerCase();if(!['woff','woff2','ttf','otf'].includes(ext))throw Error('Bitte WOFF, WOFF2, TTF oder OTF verwenden.');if(file.size>15*1024*1024)throw Error('Bitte eine Schrift unter 15 MB wählen.');const src=await toDataURL(file),existing=files().find(f=>f.src.slice(f.src.indexOf(','))===src.slice(src.indexOf(',')));if(existing)return {font:existing,reused:true};const font={id:'font-'+crypto.randomUUID(),name:file.name.replace(/\.[^.]+$/,'').replace(/[_]/g,' '),filename:file.name,src,size:file.size,format:ext};const face=new FontFace(familyName(font),await file.arrayBuffer());try{await face.load()}catch{throw Error('Diese Schrift kann der Browser nicht lesen. Die bisherige Auswahl bleibt erhalten.')}if(files().some(f=>f.name===font.name)){const base=font.name;let n=2;while(files().some(f=>f.name===font.name))font.name=base+' ('+(n++)+')'}document.fonts.add(face);loaded.set(font.id,Promise.resolve(face));files().push(font);return {font,reused:false}}
 async function importFiles(input){if(busy)return;busy=true;$('#font-files').disabled=true;let count=0,reused=0;const errors=[];for(const file of [...input]){message('Prüfe '+file.name+' …');try{const result=await importFont(file);previewId=result.font.id;result.reused?reused++:count++}catch(e){errors.push(file.name+': '+e.message)}}busy=false;$('#font-files').disabled=false;apply();renderCatalog();E.persist();message([count?count+' Schrift(en) importiert. Jetzt in der gewünschten Schriftauswahl zuweisen.':'',reused?reused+' Schrift(en) bereits vorhanden.':'',...errors].filter(Boolean).join(' '));$('#font-files').value=''}
 manage.onclick=open;$('#font-global').onchange=e=>{config().global=e.target.value;changed()};$('#font-current').onchange=e=>setIndividual(e.target.value);$('#editor-font').onchange=e=>setIndividual(e.target.value);$('#font-current-type').onchange=e=>{const el=selected();if(el){E.textData(el).fontType=e.target.value;changed()}};$('#font-done').onclick=()=>dialog.close();$('#font-files').onchange=e=>importFiles(e.target.files);const drop=$('#font-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');importFiles(e.dataTransfer.files)};
 window.DeckFonts={apply,open,selectionChanged,ready:()=>pending===0&&!busy,effective,type};apply();E.resetHistory();
});
