/* A shared default plus complete, independent overrides keyed by stable slide ID. */
window.addEventListener('DOMContentLoaded',()=>{
 const E=DeckEditor,$=s=>document.querySelector(s),copy=x=>JSON.parse(JSON.stringify(x));
 const defaults={src:'',x:54,y:804,width:130,height:62,variant:'original',white:false};
 const logo=$('#global-logo');let scope='global',dialogSlide=null,suppressClick=false;
 const state=()=>E.state(),overrides=()=>state().slideLogos||=( {} );
 const currentId=()=>window.deck?.getCurrentSlide()?.dataset.slideId||$('.slides>section.present')?.dataset.slideId||$('.slides>section')?.dataset.slideId;
 function resolve(id=currentId()){const local=overrides()[id];if(local?.mode==='hidden')return null;const value=local?.mode==='custom'?local:state().logo;return value?.src?{...defaults,...value}:null}
 function data(){return scope==='global'?state().logo:resolve(dialogSlide)}
 function editable(targetScope=scope,id=dialogSlide){if(targetScope==='global')return state().logo||=( {...defaults} );const existing=overrides()[id];if(existing?.mode==='custom')return existing;return overrides()[id]={...copy(resolve(id)||state().logo||defaults),mode:'custom'}}
 function paint(node,value){const d={...defaults,...value};node.style.left=d.x+'px';node.style.top=d.y+'px';node.style.bottom='auto';node.style.width=d.width+'px';node.style.height=d.height+'px';node.classList.toggle('has-logo',!!value?.src);node.classList.toggle('logo-white',!!d.white);node.dataset.variant=d.variant;const img=node.querySelector('img');if(value?.src){if(img.getAttribute('src')!==value.src)img.src=value.src}else img.removeAttribute('src')}
 const grip=document.createElement('button');grip.id='logo-resize';grip.textContent='↘';grip.setAttribute('aria-label','Logogröße ziehen');grip.title='Größe auf dieser Folie ändern';$('.slides').append(grip);
 const dialog=document.createElement('dialog');dialog.id='logo-dialog';dialog.innerHTML=`<button class="close" aria-label="Schließen">×</button><div class="logo-kicker">VIBE STUDIO / LOGO</div><h2>Ein Zeichen. Dein Platz.</h2><label class="logo-select">Gilt für<select id="logo-scope" aria-label="Logo-Geltungsbereich"><option value="global">Globaler Standard</option><option value="slide">Nur diese Folie</option></select></label><div id="logo-slide-controls"><label class="logo-select">Auf dieser Folie<select id="logo-mode" aria-label="Logo auf dieser Folie"><option value="inherit">Globales Logo übernehmen</option><option value="custom">Individuell anpassen</option><option value="hidden">Logo ausblenden</option></select></label></div><p id="logo-scope-hint"></p><div class="logo-content"><div><div id="logo-preview"></div><label class="logo-upload">Bild auswählen<input id="logo-file" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label><button id="logo-media">Aus Medien wählen</button></div><div class="logo-settings"><label class="logo-select">Darstellung<select id="logo-variant" aria-label="Logo-Darstellung"><option value="original">Originalfarben</option><option value="light">Hell · einfarbig weiß</option><option value="dark">Dunkel · einfarbig schwarz</option></select></label><div class="logo-coordinates"><label>X<input id="logo-x" type="number" min="0" max="1580" step="1" aria-label="Logo X-Position"></label><label>Y<input id="logo-y" type="number" min="0" max="880" step="1" aria-label="Logo Y-Position"></label><label>Breite<input id="logo-width" type="number" min="20" max="1600" step="1" aria-label="Logo-Breite"></label><label>Höhe<input id="logo-height" type="number" min="20" max="900" step="1" aria-label="Logo-Höhe"></label></div><label class="logo-control"><input id="logo-white" type="checkbox"> Helle Fläche hinter dem Logo</label><button id="logo-anchor">Unten links platzieren</button></div></div><div class="logo-bottom"><button id="logo-remove">Logo entfernen</button><button id="logo-done">Fertig</button></div><p id="logo-message">Auf der Folie ziehen zum Verschieben; mit dem Eckgriff skalieren. Ziehen passt nur diese Folie an.</p>`;document.body.append(dialog);
 function render(){const d=resolve();paint(logo,d);logo.title='Klicken: Logo dieser Folie · Ziehen: verschieben';logo.querySelector('span').textContent=overrides()[currentId()]?.mode==='hidden'?'Logo aus':'+ Logo';const g=d||defaults;grip.hidden=!E.isEditing()||!d;grip.style.left=(g.x+g.width-12)+'px';grip.style.top=(g.y+g.height-12)+'px';if(dialog.open)renderDialog()}
 function renderDialog(){const local=overrides()[dialogSlide],d={...defaults,...data()},isLocal=scope==='slide',mode=local?.mode||'inherit',disabled=!d.src||(isLocal&&mode!=='custom');$('#logo-scope').value=scope;$('#logo-slide-controls').hidden=!isLocal;$('#logo-mode').value=mode;$('#logo-scope-hint').textContent=isLocal?(mode==='inherit'?'Diese Folie folgt dem globalen Standard. Für eigene Farbe, Größe oder Position „Individuell anpassen“ wählen.':mode==='hidden'?'Das Logo bleibt auf dieser Folie in der Präsentation unsichtbar.':'Eigenes Logo und eigene Platzierung für diese Folie. Andere Folien bleiben unabhängig.'):'Gilt für alle Folien, die den globalen Standard übernehmen.';
  const preview=$('#logo-preview');preview.replaceChildren();preview.dataset.variant=d.variant;preview.classList.toggle('logo-white',d.white);if(d.src){const im=new Image();im.src=d.src;im.alt='Logo-Vorschau';preview.append(im)}else preview.textContent='Dein Logo';
  for(const key of ['x','y','width','height']){const input=$('#logo-'+key);input.value=d[key];input.disabled=disabled}$('#logo-variant').value=d.variant;$('#logo-variant').disabled=disabled;$('#logo-white').checked=!!d.white;$('#logo-white').disabled=disabled;$('#logo-anchor').disabled=disabled;$('#logo-file').disabled=isLocal&&mode==='hidden';$('#logo-media').disabled=isLocal&&mode==='hidden';$('#logo-remove').disabled=!data()?.src;$('#logo-remove').textContent=isLocal?'Auf dieser Folie ausblenden':'Globales Logo entfernen';
 }
 function open(targetScope='slide'){scope=targetScope;dialogSlide=currentId();E.select(null);renderDialog();dialog.showModal()}
 function setAsset(asset,targetScope='global',id=currentId()){const value=editable(targetScope,id);value.src=asset.src;value.name=asset.name||'Logo.png';render();E.commit();E.status(targetScope==='global'?'Globales Logo aktualisiert':'Logo auf dieser Folie aktualisiert')}
 async function load(file){if(!file)return;const targetScope=scope,id=dialogSlide;if(file.size>8*1024*1024){$('#logo-message').textContent='Bitte ein Logo unter 8 MB wählen.';return}if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(file.type)){$('#logo-message').textContent='Bitte PNG, JPG, WebP oder SVG wählen.';return}const url=URL.createObjectURL(file);try{const im=new Image();im.src=url;await im.decode();const ratio=Math.min(1,1200/im.width,600/im.height),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.width*ratio));canvas.height=Math.max(1,Math.round(im.height*ratio));canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);setAsset({src:canvas.toDataURL('image/png'),name:file.name.replace(/\.[^.]+$/,'')+'.png'},targetScope,id);$('#logo-message').textContent='Logo eingefügt. Mit „HTML speichern“ dauerhaft sichern.'}catch{$('#logo-message').textContent='Das Bild konnte nicht geladen werden. Bitte ein anderes Format versuchen.'}finally{URL.revokeObjectURL(url);$('#logo-file').value=''}}
 function drag(e,kind){if(!E.isEditing()||!resolve()||e.button!==0)return;e.preventDefault();E.select(null);document.activeElement?.blur();const id=currentId(),scale=window.deck.getScale(),start=copy(resolve(id)),px=e.clientX,py=e.clientY,target=e.currentTarget;let moved=false;target.setPointerCapture(e.pointerId);
  const move=ev=>{const dx=(ev.clientX-px)/scale,dy=(ev.clientY-py)/scale;if(!moved&&Math.hypot(ev.clientX-px,ev.clientY-py)<3)return;moved=true;const d=editable('slide',id);if(kind==='move'){d.x=Math.round(Math.max(0,Math.min(1600-d.width,start.x+dx)));d.y=Math.round(Math.max(0,Math.min(900-d.height,start.y+dy)))}else{d.width=Math.round(Math.max(20,Math.min(1600-d.x,start.width+dx)));d.height=Math.round(Math.max(20,Math.min(900-d.y,start.height+dy)))}render()};
  const end=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end);if(moved){suppressClick=true;E.commit();E.status('Logo nur auf dieser Folie angepasst');setTimeout(()=>suppressClick=false,0)}};target.addEventListener('pointermove',move);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);
 }
 logo.addEventListener('pointerdown',e=>drag(e,'move'));logo.onclick=()=>{if(E.isEditing()&&!suppressClick)open(state().logo||overrides()[currentId()]?'slide':'global')};grip.onpointerdown=e=>drag(e,'resize');
 $('#logo-scope').onchange=e=>{scope=e.target.value;renderDialog()};$('#logo-mode').onchange=e=>{const mode=e.target.value;if(mode==='inherit')delete overrides()[dialogSlide];else if(mode==='hidden')overrides()[dialogSlide]={mode:'hidden'};else editable('slide',dialogSlide);render();E.commit()};
 for(const key of ['x','y','width','height']){const input=$('#logo-'+key);input.oninput=()=>{const value=Number(input.value);if(input.value===''||!Number.isFinite(value)||value<Number(input.min)||value>Number(input.max))return;editable()[key]=value;paint(logo,resolve());const d=resolve()||defaults;grip.style.left=(d.x+d.width-12)+'px';grip.style.top=(d.y+d.height-12)+'px'};input.onchange=()=>{E.commit();render()}}
 $('#logo-variant').onchange=e=>{editable().variant=e.target.value;render();E.commit()};$('#logo-white').onchange=e=>{editable().white=e.target.checked;render();E.commit()};$('#logo-anchor').onclick=()=>{const d=editable();d.x=54;d.y=Math.max(0,900-d.height-34);render();E.commit()};$('#logo-remove').onclick=()=>{if(scope==='global')state().logo=null;else overrides()[dialogSlide]={mode:'hidden'};render();E.commit()};$('#logo-file').onchange=e=>load(e.target.files[0]);$('#logo-done').onclick=()=>dialog.close();
 $('#logo-media').onclick=()=>{const targetScope=scope,id=dialogSlide;dialog.close();VibeMedia.open('logo',asset=>{setAsset(asset,targetScope,id);scope=targetScope;dialogSlide=id;renderDialog();dialog.showModal()})};
 function thumbnail(id){const d=resolve(id);if(!d)return null;const node=document.createElement('div');node.className='logo-thumbnail';node.innerHTML='<img alt="">';paint(node,d);return node}
 window.DeckLogos={open,render,resolve,setAsset,thumbnail};render();E.resetHistory();
});
