/* One reusable media catalog. Imported bytes are stored once in the exported document state. */
window.addEventListener('DOMContentLoaded',()=>{
 const E=DeckEditor,$=s=>document.querySelector(s),builtins=[];
 const state=()=>E.state();state().assets||=[];
 const readable={'scene-paper.jpg':'Keramik · Tellerrand','scene-wood.jpg':'Holz · Jahresringe','scene-blueprint.jpg':'Wasserringe','scene-landscape.jpg':'Pflanzenquerschnitt','scene-orbit.jpg':'Planetenkante','scene-network.jpg':'Netzknoten · Kreisbogen','scene-dawn.jpg':'Morgenlicht · Horizont','scene-sun.jpg':'Sonne · Sonnenflecken'};
 document.querySelectorAll('.slides>section img,.slides>section video').forEach((el,i)=>{const src=el.getAttribute('src');if(!src||builtins.some(a=>a.src===src))return;const filename=el.dataset.fileName||src.split('/').pop().split('?')[0];builtins.push({id:'builtin-'+builtins.length,name:filename.startsWith('data:')?'Motiv '+(i+1):filename,label:readable[filename]||filename,kind:el.tagName==='VIDEO'?'video':'image',src,width:el.naturalWidth||1600,height:el.naturalHeight||900,size:src.startsWith('data:')?Math.round(src.length*.75):0,builtin:true})});
 function logoSources(){return [state().logo,...Object.values(state().slideLogos||{})].filter(l=>l?.src)}
 function isLogo(a){return !!a.logo||logoSources().some(l=>l.src===a.src)}
 function all(){const list=[...builtins,...(state().assets||[])];for(const logo of logoSources()){const existing=list.find(a=>a.src===logo.src);if(existing){existing.logo=true;continue}const a={id:'asset-'+crypto.randomUUID(),name:logo.name||'Eigenes Logo.png',label:logo.name||'Eigenes Logo',kind:'image',logo:true,src:logo.src,size:Math.round(logo.src.length*.75)};state().assets.push(a);list.push(a)}return list}
 function get(id){return all().find(a=>a.id===id)}
 function read(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=()=>reject(Error('Datei konnte nicht gelesen werden.'));fr.readAsDataURL(file)})}
 function imageProbe(url){return new Promise((resolve,reject)=>{const im=new Image(),timer=setTimeout(()=>reject(Error('Zeitüberschreitung beim Bild.')),8000);im.onload=()=>{clearTimeout(timer);resolve({width:im.naturalWidth,height:im.naturalHeight,kind:'image'})};im.onerror=()=>{clearTimeout(timer);reject(Error('Kein darstellbares Bild.'))};im.src=url})}
 function videoProbe(url){return new Promise((resolve,reject)=>{const v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';const done=()=>{v.pause();v.removeAttribute('src');v.load()};const timer=setTimeout(()=>{done();reject(Error('Videocodec nicht unterstützt.'))},10000);v.onloadeddata=()=>{clearTimeout(timer);if(!v.videoWidth){done();reject(Error('Keine Videospur gefunden.'));return}const c=document.createElement('canvas');c.width=400;c.height=Math.max(1,Math.round(400*v.videoHeight/v.videoWidth));c.getContext('2d').drawImage(v,0,0,c.width,c.height);const result={kind:'video',width:v.videoWidth,height:v.videoHeight,duration:Number.isFinite(v.duration)?v.duration:0,thumb:c.toDataURL('image/jpeg',.75)};done();resolve(result)};v.onerror=()=>{clearTimeout(timer);done();reject(Error('Videoformat oder Codec nicht unterstützt.'))};v.src=url})}
 async function importFile(file){if(file.size>100*1024*1024)throw Error('Bitte die Datei auf unter 100 MB kürzen oder verkleinern.');const ext=file.name.split('.').pop().toLowerCase();const knownImages=/^(png|jpe?g|gif|webp|avif|apng|bmp|ico|svg|heic|heif|tiff?)$/;const knownVideos=/^(mp4|webm|m4v|mov|ogv|ogg|avi|mkv|mpeg|mpg|3gp)$/;if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')&&!knownImages.test(ext)&&!knownVideos.test(ext))throw Error('Kein Bild oder Video. Bitte als Bild oder MP4/WebM exportieren.');
  let mime=file.type||({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',svg:'image/svg+xml',webm:'video/webm',mp4:'video/mp4',mov:'video/quicktime',gif:'image/gif'}[ext])||'application/octet-stream';let typed=new Blob([file],{type:mime});const url=URL.createObjectURL(typed);let info;
  try{info=file.type.startsWith('video/')||knownVideos.test(ext)?await videoProbe(url):await imageProbe(url)}catch{throw Error('Der Browser kann diese Datei nicht darstellen. Bild als PNG/JPG/WebP oder Video als MP4 (H.264) bzw. WebM exportieren.')}finally{URL.revokeObjectURL(url)}
  if(info.kind==='image'&&Math.max(info.width,info.height)>LONG_SIDE&&/^image\/(jpeg|png|bmp)$/.test(mime)){try{const small=await shrink(typed,info,mime);typed=small.blob;mime=small.mime;info={...info,width:small.width,height:small.height,scaledFrom:info.width+' × '+info.height}}catch{}}
  const src=await read(typed),existing=all().find(a=>a.src===src);if(existing)return existing;const asset={id:'asset-'+crypto.randomUUID(),name:file.name,label:file.name,mime,size:typed.size,src,...info};state().assets.push(asset);E.persist();return asset;
 }
 /* Uploads above 3200 px on the long side are scaled down before they enter the deck: slides are 1600×900, so a 12-megapixel phone photo only costs memory, its first-time decode stalls the crossfade, and the exported HTML grows. Formats that may animate (GIF, APNG, WebP, AVIF) and SVG stay untouched. */
 const LONG_SIDE=3200;
 async function shrink(blob,info,mime){const scale=LONG_SIDE/Math.max(info.width,info.height),width=Math.round(info.width*scale),height=Math.round(info.height*scale);const bitmap=await createImageBitmap(blob,{resizeWidth:width,resizeHeight:height,resizeQuality:'high'});const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(bitmap,0,0,width,height);bitmap.close?.();const type=mime==='image/png'?'image/png':'image/jpeg';const out=await new Promise(r=>canvas.toBlob(r,type,.9));if(!out)throw Error('Bild konnte nicht verkleinert werden.');return{blob:out,width,height,mime:type}}
 let selectedId=null,intent='browse',logoCallback=null;
 const dialog=document.createElement('dialog');dialog.id='media-dialog';dialog.innerHTML=`<button class="close" aria-label="Schließen">×</button><div class="media-heading"><div><div class="studio-kicker">VIBE STUDIO / MEDIEN</div><h2>Alles an einem Ort.</h2></div><label class="studio-upload">Dateien hinzufügen<input id="media-files" type="file" multiple></label></div><div class="media-filters"><input id="media-search" type="search" placeholder="Dateiname oder Motiv suchen …" aria-label="Medien durchsuchen"><select id="media-filter" aria-label="Medientyp"><option value="all">Alle Medien</option><option value="image">Bilder</option><option value="video">Videos</option><option value="logo">Logos</option></select><span id="media-count"></span></div><div id="media-drop"><div id="asset-grid"></div></div><div class="media-footer"><div><div id="media-selected">Ein Medium auswählen</div><div id="media-message" role="status">Dateien hierher ziehen. Bilder und Videos werden vor dem Einfügen geprüft.</div></div><div class="media-actions"><button id="asset-download">Datei speichern</button><button id="asset-logo">Als Logo</button><button id="asset-insert" aria-label="Auf Folie einfügen">Einfügen</button><button id="asset-background">Als Hintergrund</button></div></div><p class="media-formats">Bilder: z. B. JPG, PNG, WebP, GIF, SVG, AVIF, BMP. Videos: z. B. MP4, WebM, OGV – weitere Formate je nach Browser und Codec. Maximal 100 MB je Datei. Alle verwendeten Medien werden in der HTML mitgespeichert.</p>`;document.body.append(dialog);
 const uploadButton=document.createElement('button');uploadButton.id='editor-media';uploadButton.textContent='Medien';uploadButton.setAttribute('aria-label','Medienübersicht');$('#editor-main')?.append(uploadButton);$('.editor-main').insertBefore(uploadButton,$('#editor-logo'));uploadButton.onclick=()=>open('browse');
 const size=n=>n>1024*1024?(n/1024/1024).toFixed(1)+' MB':Math.max(1,Math.round((n||0)/1024))+' KB';
 function render(){const q=$('#media-search').value.toLowerCase(),filter=$('#media-filter').value;const assets=all().filter(a=>(a.name+' '+(a.label||'')).toLowerCase().includes(q)&&(filter==='all'||a.kind===filter||filter==='logo'&&isLogo(a)));const grid=$('#asset-grid');grid.replaceChildren();$('#media-count').textContent=assets.length+' Medien';for(const a of assets){const card=document.createElement('button');card.className='asset-card';card.dataset.assetId=a.id;card.setAttribute('aria-label',a.name);card.setAttribute('aria-pressed',String(a.id===selectedId));const img=new Image();img.src=a.thumb||a.src;img.alt='';img.loading='lazy';const label=document.createElement('b');label.textContent=a.label||a.name;const meta=document.createElement('span');meta.textContent=(a.kind==='video'?'Video':'Bild')+' · '+size(a.size)+(isLogo(a)?' · Logo':'');card.append(img,label,meta);card.onclick=()=>{selectedId=a.id;render()};grid.append(card)}const a=get(selectedId);$('#media-selected').textContent=a?a.name+(a.width?' · '+a.width+' × '+a.height:'')+(a.scaledFrom?' (verkleinert von '+a.scaledFrom+')':'')+(a.duration?' · '+a.duration.toFixed(1)+' s':''):'Ein Medium auswählen';for(const id of ['asset-download','asset-insert','asset-background'])$('#'+id).disabled=!a;$('#asset-logo').disabled=!a||a.kind!=='image';}
 function open(mode='browse',callback=null){intent=mode;logoCallback=callback;$('#media-search').value='';$('#media-filter').value=mode==='logo'?'image':'all';$('#asset-logo').textContent=mode==='logo'?'Dieses Logo verwenden':'Als globales Logo';$('#asset-insert').hidden=$('#asset-background').hidden=mode==='logo';selectedId=null;$('#media-message').textContent='Dateien hierher ziehen oder ein vorhandenes Medium wählen.';render();dialog.showModal()}
 async function importFiles(files){const list=[...files],results=[],errors=[];for(let i=0;i<list.length;i++){const file=list[i];$('#media-message').textContent=`Prüfe ${i+1}/${list.length}: ${file.name}`;try{const a=await importFile(file);results.push(a);selectedId=a.id}catch(e){errors.push(file.name+': '+e.message)}}render();$('#media-message').textContent=errors.length?errors.join(' / '):results.length+' Datei(en) bereit.';return results}
 $('#media-files').onchange=async e=>{await importFiles(e.target.files);e.target.value=''};$('#media-search').oninput=render;$('#media-filter').onchange=render;
 const drop=$('#media-drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=async e=>{e.preventDefault();drop.classList.remove('dragover');await importFiles(e.dataTransfer.files)};
 $('#asset-insert').onclick=()=>{const a=get(selectedId);if(a){E.addMedia(a);dialog.close()}};$('#asset-background').onclick=()=>{const a=get(selectedId);if(a){VibeStudio.setBackground(a);dialog.close()}};$('#asset-logo').onclick=()=>{const a=get(selectedId);if(a?.kind==='image'){const callback=logoCallback;dialog.close();if(intent==='logo'&&callback)callback(a);else E.setLogo(a)}};$('#asset-download').onclick=()=>{const a=get(selectedId);if(!a)return;const link=document.createElement('a');link.href=a.src;link.download=a.name;link.click()};
 window.VibeMedia={all,get,importFile,open,render,find:src=>all().find(a=>a.src===src)};
});
