/* Shared controls are available before the DOMContentLoaded editor hooks run. Defaults are deliberately lively but calm: a Ken Burns drift you notice within a few seconds, soft light spots and dust that just register, grain, and a slow light sweep (shine) across the motif. */
window.VibeMotionSettings={
 tuned:{network:{movement:72,rotation:60,dof:32,dust:36,shine:26},dawn:{movement:76,rotation:13,dof:30,dust:14,shine:40},sun:{movement:70,dof:10,dust:10,shine:14},moon:{movement:70,rotation:80,dof:8,dust:8,shine:14},earth:{movement:68,rotation:75,dof:8,dust:6,shine:12},nightearth:{movement:70,rotation:80,dof:10,dust:10,shine:12},vault:{movement:64,rotation:85,dof:16,dust:34,shine:26},dial:{movement:64,rotation:85,dof:16,dust:16,shine:32},astrolabe:{movement:64,rotation:85,dof:16,dust:18,shine:34},sunflower:{movement:68,rotation:75,dof:22,dust:16,shine:30},manhole:{movement:66,rotation:80,dof:10,dust:10,texture:8,shine:20},blueprint:{rotation:50,waves:62,shine:30},plan:{movement:66,rotation:55,dof:14,dust:10,texture:16,shine:30},light:{movement:70,rotation:60,dof:38,dust:32,shine:44},fan:{movement:68,rotation:60,dof:20,dust:14,shine:34},track:{movement:66,rotation:65,dof:16,dust:12,shine:30},record:{movement:66,rotation:80,dof:18,dust:12,shine:42},lens:{movement:64,rotation:50,dof:26,dust:12,shine:40},arch:{movement:68,rotation:45,dof:36,dust:26,shine:44}},
 /* Centre and radius of each motif's disc or arc in frame percent (x, y) and pixels (radius), optionally the height the zoom is anchored at (percent, default 50): the camera turns the picture around this centre, so the disc itself visibly rotates. The sunrise zooms around the horizon so the hills stay in view. */
 pivots:{paper:[50,241.7,1602],wood:[50,237.1,1564],orbit:[50,238.9,1565],landscape:[50,179.9,1021],blueprint:[50,188.9,1100],dawn:[50,88.9,275,72],sun:[50,168.89,900],moon:[43.75,570.82,4537],earth:[36.25,120,560],nightearth:[52.5,469.19,3663],dial:[50,120,560],astrolabe:[50,124.44,600],sunflower:[50,155.56,760],manhole:[50,126.67,620],network:[50,173.3,960],light:[50,175.6,980],plan:[56.25,148.89,700],fan:[50,130,600],track:[50,160.6,840],vault:[50,113.33,500],record:[50,144.4,735],lens:[50,131.1,600],arch:[50,124.44,550]},
 pivot(node){const scene=node?.dataset.scene||node?.className||'';for(const [key,value] of Object.entries(this.pivots))if(scene.split(/\s+/).includes(key))return value;return [50,50,1800]},
 defaults(node){const scene=node?.dataset.scene||node?.className||'';const base={motion:!!node?.querySelector('.motion-layer img'),cycle:18,strength:95,movement:80,rotation:70,speed:1,waves:0,dof:24,dust:18,texture:12,vividness:16,jiggle:0,shine:34};for(const [key,values] of Object.entries(this.tuned))if(scene.split(/\s+/).includes(key))Object.assign(base,values);return base},
 normalize(value){const c={...this.defaults(null),...value};for(const k of ['strength','movement','rotation','waves','dof','dust','texture','vividness','jiggle','shine'])c[k]=Math.max(0,Math.min(100,Number(c[k])||0));c.speed=Math.max(.25,Math.min(2,Number(c.speed)||1));c.cycle=Math.max(10,Math.min(180,Number(c.cycle)||18));return c},
 presets:{calm:{strength:70,movement:48,rotation:35,speed:.8,waves:14,dof:12,dust:10,texture:8,vividness:8,jiggle:0,shine:16},vivid:{strength:95,movement:80,rotation:70,speed:1,waves:34,dof:24,dust:18,texture:12,vividness:16,jiggle:0,shine:34},handheld:{strength:95,movement:54,rotation:35,speed:1,waves:0,dof:24,dust:18,texture:12,vividness:12,jiggle:26,shine:24}}
};
window.addEventListener('DOMContentLoaded',()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),scenes=new Map();let paused=reduced.matches,preview=false,raf=0,last=0;
 const root=()=>document.querySelector('.reveal>.slides');
 const running=()=>preview||!paused;
 /* Animated elements are promoted to compositor layers by their running animations alone; no will-change, no filters and no blend modes on the dust and light spots, so a slide costs one filtered image layer, one soft-light grain layer and plain alpha-blended particles. */
 /* Slides that just left stay in motion until their crossfade has ended (see sync); pausing them mid-fade would freeze and re-rasterise their layers. */
 const leaving=new Map();
 function fadeMs(section){const v=parseFloat(section?.style.getPropertyValue('--studio-transition-ms'));return Number.isFinite(v)?v:1200}
 function active(el){const section=el.closest('section'),layer=el.closest('.motion-layer,.studio-background');return !!section&&(section.classList.contains('present')||leaving.has(layer))&&running()&&!document.hidden&&!document.querySelector('.reveal')?.classList.contains('overview')&&layer?.style.display!=='none'}
 /* Photos of the current and neighbouring slides are decoded ahead of the crossfade; a first-time decode of a large upload otherwise stalls the fade. */
 function prefetch(){const slides=[...root().querySelectorAll(':scope>section')],i=slides.findIndex(s=>s.classList.contains('present'));if(i<0)return;for(const s of [slides[i],slides[i-1],slides[i+1]])s?.querySelectorAll(':scope>.motion-layer>img,:scope>.studio-background>img,:scope>.motion-layer>.motion-camera>img,:scope>.studio-background>.motion-camera>img').forEach(img=>{if(img.complete&&img.naturalWidth&&!img.dataset.decoded){img.dataset.decoded='1';img.decode?.().catch(()=>{})}})}
 function animate(record,el,frames,seconds,phase=0){const a=el.animate(frames,{duration:seconds*1000/record.cfg.speed,iterations:Infinity,direction:'alternate',easing:'ease-in-out',fill:'both'});a.pause();a.currentTime=record.time*1000/record.cfg.speed+phase;record.animations.push(a);return a}
 /* The media, its colour filter and the grain live inside one animated wrapper (.motion-camera). They rasterise together into a single compositor layer, so neither the saturate() filter nor the soft-light grain needs a render surface or a backdrop copy per frame; only the wrapper's transform runs on the compositor. */
 const MEDIA=':scope>img,:scope>video,:scope>.motion-camera>img,:scope>.motion-camera>video';
 function stage(record){let camera=record.layer.querySelector(':scope>.motion-camera');if(!camera){camera=document.createElement('div');camera.className='motion-camera';camera.dataset.motionCamera='';record.media.replaceWith(camera);camera.append(record.media)}return camera}
 function unstage(record){const camera=record.layer.querySelector(':scope>.motion-camera');if(camera)camera.replaceWith(...camera.childNodes)}
 function colour(record){const c=record.cfg,saturation=1+c.vividness/100*record.amount*.28,filter=saturation>1.005?`saturate(${saturation.toFixed(3)})`:'';record.media.style.filter=filter;if(record.wave)record.wave.canvas.style.filter=filter}
 /* Smallest scale that keeps the 1600 × 900 frame covered when the picture is turned by a degrees around (px, py), then scaled around (800, oy) and shifted by (tx, ty). */
 function cover(a,px,py,tx,ty,oy){const rad=-a*Math.PI/180,cs=Math.cos(rad),sn=Math.sin(rad),corners=[[0,0],[1600,0],[0,900],[1600,900]],ok=k=>corners.every(([qx,qy])=>{const ux=(qx-800-tx)/k+800-px,uy=(qy-oy-ty)/k+oy-py,x=px+ux*cs-uy*sn,y=py+ux*sn+uy*cs;return x>=-.5&&x<=1600.5&&y>=-.5&&y<=900.5});let lo=1,hi=2;if(ok(lo))return lo;for(let n=0;n<26;n++){const mid=(lo+hi)/2;if(ok(mid))hi=mid;else lo=mid}return hi}
 /* The camera turns the picture around the centre of its disc (VibeMotionSettings.pivots), so plate, wood slice, vault door, dial or planet visibly rotate; rotation sets how far the rim travels (up to 80 px, at most 6°; very large discs such as planet limbs still turn at least 1.5°), movement adds a gentle drift and zoom. Uploaded backgrounds turn around the frame centre. The zoom is recomputed for both end positions so no picture edge ever shows. */
 function camera(record,el,index){const c=record.cfg,m=c.movement/100*record.amount,r=c.rotation/100*record.amount,j=c.jiggle/100*record.amount,sign=index%2?-1:1,[pxp,pyp,radius,oyp=50]=VibeMotionSettings.pivot(record.layer.classList.contains('studio-background')?null:record.layer.closest('section')),px=pxp/100*1600,py=pyp/100*900,oy=oyp/100*900;
  el.style.transformOrigin='0 0';
  const deg=Math.min(6,Math.max(1.5*r,r*80/radius*180/Math.PI)),tx=18*m,ty=5*m,T=(x,y,k,a)=>`translate(${(800+x).toFixed(2)}px,${(oy+y).toFixed(2)}px) scale(${k.toFixed(4)}) translate(-800px,${(-oy).toFixed(1)}px) translate(${px.toFixed(1)}px,${py.toFixed(1)}px) rotate(${a.toFixed(3)}deg) translate(${(-px).toFixed(1)}px,${(-py).toFixed(1)}px)`;
  const a0=-deg*sign,a1=deg*sign,x0=-tx*sign,x1=tx*sign,moving=m||r||j,k0=moving?cover(a0,px,py,x0,ty,oy)+.012+.03*j:1,k1=moving?Math.max(cover(a1,px,py,x1,-ty,oy)+.012+.03*j,k0+.08*m):1;
  animate(record,el,[{transform:T(x0,ty,k0,a0)},{transform:T(x1,-ty,k1,a1)}],c.cycle/2)
 }
 function waveSurface(record){const c=record.cfg;if(record.wave||!c.waves||!record.amount)return;const canvas=document.createElement('canvas');canvas.className='motion-wave';canvas.dataset.motionRuntime='';canvas.width=1600;canvas.height=900;const gl=canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:false});if(!gl)return;
  const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Wave shader');return s};
  try{const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 a;varying vec2 uv;void main(){uv=(a+1.0)*.5;gl_Position=vec4(a,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 uv;uniform sampler2D image;uniform float time,amount;uniform vec2 crop,position;void main(){vec2 p=uv;float mask=smoothstep(.24,.68,1.-p.y);p.x+=(sin(p.y*28.+time*.45)+sin((p.x+p.y)*19.-time*.30)*.6)*amount*mask;p.y+=sin(p.x*31.-time*.50)*amount*.35*mask;p=p*crop+(1.-crop)*position;if(p.x<0.||p.x>1.||p.y<0.||p.y>1.){gl_FragColor=vec4(0.);return;}gl_FragColor=texture2D(image,p);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Wave program');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.bindTexture(gl.TEXTURE_2D,gl.createTexture());gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);
   const u=Object.fromEntries(['time','amount','crop','position'].map(k=>[k,gl.getUniformLocation(program,k)]));let loaded=false;const media=record.media;
   record.wave={canvas,gl,draw(t){if(media.tagName==='VIDEO'?media.readyState<2:!media.complete||!media.naturalWidth)return;try{if(!loaded||media.tagName==='VIDEO'){gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,media);loaded=true}const ratio=(media.videoWidth||media.naturalWidth)/(media.videoHeight||media.naturalHeight),view=16/9;let x=1,y=1;if(c.fit==='contain'){if(ratio>view)y=ratio/view;else x=view/ratio}else if(c.fit!=='fill'){if(ratio>view)x=view/ratio;else y=ratio/view}gl.uniform2f(u.crop,x,y);gl.uniform2f(u.position,(c.x??50)/100,1-(c.y??50)/100);gl.uniform1f(u.time,t);gl.uniform1f(u.amount,c.waves/100*record.amount*.008);gl.viewport(0,0,canvas.width,canvas.height);gl.drawArrays(gl.TRIANGLES,0,6);canvas.style.visibility='visible'}catch{canvas.style.visibility='hidden'}},dispose(){gl.getExtension('WEBGL_lose_context')?.loseContext()}};
   canvas.style.visibility='hidden';media.after(canvas);record.wave.draw(record.time);
  }catch{gl.getExtension('WEBGL_lose_context')?.loseContext()}
 }
 function atmosphere(record){const c=record.cfg,a=record.amount,box=document.createElement('div');box.className='motion-atmosphere';box.dataset.motionRuntime='';record.layer.append(box);
  if(c.texture){const grain=document.createElement('div');grain.className='motion-grain';grain.dataset.motionRuntime='';grain.style.opacity=c.texture/100*a*.24;stage(record).append(grain)}
  /* Soft light spots drift and breathe (opacity 55–100 %), dust specks rise and twinkle; both are plain alpha-blended elements animated with transform and opacity only. */
  if(c.dof)for(let i=0;i<3;i++){const spot=document.createElement('i'),o=c.dof/100*a*.42;spot.className='motion-dof';spot.style.cssText=`left:${[8,66,39][i]}%;top:${[70,56,82][i]}%;width:${[300,230,380][i]}px;height:${[300,230,380][i]}px;opacity:${o}`;box.append(spot);animate(record,spot,[{transform:'translate3d(-40px,16px,0) scale(.9)',opacity:o*.55},{transform:'translate3d(60px,-34px,0) scale(1.12)',opacity:o}],16+i*5)}
  if(c.dust)for(let i=0;i<12;i++){const dot=document.createElement('i'),size=[5,10,7,15][i%4],o=c.dust/100*a*(i%3===0?.75:.42);dot.className='motion-dust';dot.style.cssText=`left:${(i*37+11)%100}%;top:${(i*23+17)%100}%;width:${size}px;height:${size}px;opacity:${o}`;box.append(dot);animate(record,dot,[{transform:'translate3d(-18px,34px,0)',opacity:o*.35},{transform:`translate3d(${20+i*2}px,-52px,0)`,opacity:o}],11+i*1.3)}
  /* Shine: a wide, soft band of light sweeps once per cycle diagonally across the motif (first sweep right after the slide appears), then rests off screen. */
  if(c.shine){const band=document.createElement('i'),o=Math.min(.6,c.shine/100*a*.55),off='translate3d(-160%,0,0) skewX(-16deg)',on='translate3d(330%,0,0) skewX(-16deg)';band.className='motion-shine';band.style.opacity='0';box.append(band);const frames=[{offset:0,transform:off,opacity:0},{offset:.16,transform:off,opacity:0},{offset:.3,opacity:o},{offset:.48,opacity:o},{offset:.6,transform:on,opacity:0},{offset:1,transform:on,opacity:0}],x=animate(record,band,frames,Math.max(12,c.cycle*.9));x.effect.updateTiming({direction:'normal',easing:'linear'});x.effect.setKeyframes(frames.map(f=>({...f,easing:'ease-in-out'})))}
 }
 function dispose(r){clearTimeout(leaving.get(r.layer));leaving.delete(r.layer);r.animations.forEach(a=>a.cancel());r.wave?.dispose();r.layer.querySelectorAll('[data-motion-runtime]').forEach(e=>e.remove());r.media.style.filter='';unstage(r)}
 function refresh(){const layers=[...root().querySelectorAll(':scope>section .motion-layer,:scope>section .studio-background')].filter(l=>l.style.display!=='none'&&l.querySelector(MEDIA));
  for(const[layer,r]of scenes)if(!layers.includes(layer)){dispose(r);scenes.delete(layer)}
  layers.forEach((layer,i)=>{const media=layer.querySelector(MEDIA),cfg=VibeMotionSettings.normalize({...VibeMotionSettings.defaults(layer.closest('section')),...JSON.parse(layer.dataset.motionSettings||'{}')}),key=JSON.stringify(cfg),old=scenes.get(layer);if(old?.key===key&&old.media===media)return;const time=old?.time??3;let r;if(old?.media===media){r=old;r.animations.forEach(a=>a.cancel());r.animations=[];r.layer.querySelectorAll('.motion-atmosphere,.motion-grain').forEach(e=>e.remove());r.media.style.filter='';Object.assign(r.cfg,cfg);r.key=key;r.amount=cfg.motion?cfg.strength/100:0;if(r.wave&&(!cfg.waves||!r.amount)){r.wave.dispose();r.wave.canvas.remove();r.wave=null}}else{old&&dispose(old);r={layer,media,cfg,key,time,amount:cfg.motion?cfg.strength/100:0,animations:[]}}scenes.set(layer,r);if(r.amount){camera(r,stage(r),i);waveSurface(r);colour(r);atmosphere(r);if(cfg.jiggle){const j=cfg.jiggle/100*r.amount,frames=Array.from({length:41},(_,n)=>{const t=n/40*Math.PI*2,x=Math.sin(t*3)*.64+Math.sin(t*7+.7)*.23+Math.sin(t*11)*.13,y=Math.cos(t*2+.4)*.68+Math.sin(t*5)*.32,angle=Math.sin(t*4+.5)*.65+Math.sin(t*9)*.35;return{transform:`translate3d(${x*j*17}px,${y*j*11}px,0) rotate(${angle*j*.7}deg) scale(${1+.035*j})`}});const a=animate(r,layer,frames,24);a.effect.updateTiming({direction:'normal',easing:'linear'});a.effect.setKeyframes(frames.map(f=>({...f,easing:'ease-in-out'})))}}
  });sync()
 }
 function tick(now){raf=0;const dt=last?Math.min(.1,(now-last)/1000):0;last=now;for(const r of scenes.values())if(active(r.layer)){r.time+=dt*r.cfg.speed;r.wave?.draw(r.time)}if([...scenes.values()].some(r=>active(r.layer)))raf=requestAnimationFrame(tick)}
 function sync(){const present=root().querySelector(':scope>section.present');for(const r of scenes.values()){const section=r.layer.closest('section');if(section&&section!==present&&r.playing&&running()&&!leaving.has(r.layer))leaving.set(r.layer,setTimeout(()=>{leaving.delete(r.layer);r.playing=false;sync()},fadeMs(section)+150));if(section===present&&leaving.has(r.layer)){clearTimeout(leaving.get(r.layer));leaving.delete(r.layer)}const play=active(r.layer);r.playing=play;r.animations.forEach(a=>{if(play)a.play();else{const t=a.currentTime;a.pause();a.currentTime=t}});r.wave?.draw(r.time)}prefetch();root().querySelectorAll(':scope>section video').forEach(v=>{v.muted=true;const r=scenes.get(v.closest('.studio-background,.motion-layer'));v.playbackRate=r?.cfg.speed||1;if(active(v))v.play().catch(()=>{});else v.pause()});if(!raf&&[...scenes.values()].some(r=>active(r.layer))){last=0;raf=requestAnimationFrame(tick)}document.documentElement.classList.toggle('motion-paused',!running());document.querySelector('#background-preview-motion')?.setAttribute('aria-pressed',String(preview))}
 window.DeckMotion={toggle(){preview=false;paused=!paused;sync();return paused},isPaused:()=>paused,setPaused(v){paused=v;sync()},setPreview(v){preview=!!v;sync();return preview},isPreviewing:()=>preview,sync,refresh,
  ready(){return [...scenes.values()].every(r=>r.media.tagName==='VIDEO'?r.media.readyState>=2:r.media.complete&&r.media.naturalWidth>0)},
  render(t){if(raf)cancelAnimationFrame(raf);raf=0;for(const r of scenes.values()){r.time=t*r.cfg.speed;r.animations.forEach(a=>{a.pause();a.currentTime=t*1000});r.wave?.draw(r.time)}}};
 document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',e=>{preview=false;paused=e.matches;sync()});refresh();
});
