/* Shared controls are available before the DOMContentLoaded editor hooks run. Defaults are deliberately lively: strong Ken Burns, visible light, dust and grain. */
window.VibeMotionSettings={
 defaults(node){const scene=node?.dataset.scene||node?.className||'';const network=scene.includes('network'),dawn=scene.includes('dawn');return{motion:!!node?.querySelector('.motion-layer img'),cycle:28,strength:95,movement:network?52:dawn?58:76,rotation:scene.includes('blueprint')?11:network?8:dawn?10:28,speed:1,waves:scene.includes('blueprint')?54:0,dof:network?18:dawn?16:10,dust:network?24:dawn?5:9,texture:12,vividness:16,jiggle:0}},
 normalize(value){const c={...this.defaults(null),...value};for(const k of ['strength','movement','rotation','waves','dof','dust','texture','vividness','jiggle'])c[k]=Math.max(0,Math.min(100,Number(c[k])||0));c.speed=Math.max(.25,Math.min(2,Number(c.speed)||1));c.cycle=Math.max(10,Math.min(180,Number(c.cycle)||28));return c},
 presets:{calm:{strength:70,movement:48,rotation:14,speed:.8,waves:14,dof:6,dust:5,texture:8,vividness:8,jiggle:0},vivid:{strength:95,movement:76,rotation:28,speed:1,waves:34,dof:10,dust:9,texture:12,vividness:16,jiggle:0},handheld:{strength:95,movement:54,rotation:14,speed:1,waves:0,dof:10,dust:9,texture:12,vividness:12,jiggle:26}}
};
window.addEventListener('DOMContentLoaded',()=>{
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),scenes=new Map();let paused=reduced.matches,preview=false,raf=0,last=0;
 const root=()=>document.querySelector('.reveal>.slides');
 const running=()=>preview||!paused;
 /* Slides that just left stay in motion until their crossfade has ended (see sync); pausing them mid-fade would freeze and re-rasterise their layers. */
 const leaving=new Map();
 function fadeMs(section){const v=parseFloat(section?.style.getPropertyValue('--studio-transition-ms'));return Number.isFinite(v)?v:1200}
 function active(el){const section=el.closest('section'),layer=el.closest('.motion-layer,.studio-background');return !!section&&(section.classList.contains('present')||leaving.has(layer))&&running()&&!document.hidden&&!document.querySelector('.reveal')?.classList.contains('overview')&&layer?.style.display!=='none'}
 /* Photos of the current and neighbouring slides are decoded ahead of the crossfade; a first-time decode of a large upload otherwise stalls the fade. */
 function prefetch(){const slides=[...root().querySelectorAll(':scope>section')],i=slides.findIndex(s=>s.classList.contains('present'));if(i<0)return;for(const s of [slides[i],slides[i-1],slides[i+1]])s?.querySelectorAll(':scope>.motion-layer>img,:scope>.studio-background>img').forEach(img=>{if(img.complete&&img.naturalWidth&&!img.dataset.decoded){img.dataset.decoded='1';img.decode?.().catch(()=>{})}})}
 function animate(record,el,frames,seconds,phase=0){const a=el.animate(frames,{duration:seconds*1000/record.cfg.speed,iterations:Infinity,direction:'alternate',easing:'ease-in-out',fill:'both'});a.pause();a.currentTime=record.time*1000/record.cfg.speed+phase;record.animations.push(a);return a}
 function camera(record,el,index){const c=record.cfg,m=c.movement/100*record.amount,r=c.rotation/100*record.amount,sign=index%2?-1:1;el.style.transformOrigin='50% 72%';el.style.filter=`saturate(${1+c.vividness/100*record.amount*.28})`;
  const pad=(m||r||c.jiggle)? .025+Math.max(m*.10,r*.07):0,base=1+pad;animate(record,el,[{transform:`translate3d(${-35*m*sign}px,${10*m}px,0) rotate(${-1.6*r*sign}deg) scale(${base})`},{transform:`translate3d(${35*m*sign}px,${-10*m}px,0) rotate(${1.6*r*sign}deg) scale(${base+.16*m})`}],c.cycle/2)
 }
 function waveSurface(record){const c=record.cfg;if(record.wave||!c.waves||!record.amount)return;const canvas=document.createElement('canvas');canvas.className='motion-wave';canvas.dataset.motionRuntime='';canvas.width=1600;canvas.height=900;const gl=canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:false});if(!gl)return;
  const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Wave shader');return s};
  try{const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 a;varying vec2 uv;void main(){uv=(a+1.0)*.5;gl_Position=vec4(a,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 uv;uniform sampler2D image;uniform float time,amount;uniform vec2 crop,position;void main(){vec2 p=uv;float mask=smoothstep(.24,.68,1.-p.y);p.x+=(sin(p.y*28.+time*.45)+sin((p.x+p.y)*19.-time*.30)*.6)*amount*mask;p.y+=sin(p.x*31.-time*.50)*amount*.35*mask;p=p*crop+(1.-crop)*position;if(p.x<0.||p.x>1.||p.y<0.||p.y>1.){gl_FragColor=vec4(0.);return;}gl_FragColor=texture2D(image,p);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Wave program');gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.bindTexture(gl.TEXTURE_2D,gl.createTexture());gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);
   const u=Object.fromEntries(['time','amount','crop','position'].map(k=>[k,gl.getUniformLocation(program,k)]));let loaded=false;const media=record.media;
   record.wave={canvas,gl,draw(t){if(media.tagName==='VIDEO'?media.readyState<2:!media.complete||!media.naturalWidth)return;try{if(!loaded||media.tagName==='VIDEO'){gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,media);loaded=true}const ratio=(media.videoWidth||media.naturalWidth)/(media.videoHeight||media.naturalHeight),view=16/9;let x=1,y=1;if(c.fit==='contain'){if(ratio>view)y=ratio/view;else x=view/ratio}else if(c.fit!=='fill'){if(ratio>view)x=view/ratio;else y=ratio/view}gl.uniform2f(u.crop,x,y);gl.uniform2f(u.position,(c.x??50)/100,1-(c.y??50)/100);gl.uniform1f(u.time,t);gl.uniform1f(u.amount,c.waves/100*record.amount*.008);gl.viewport(0,0,canvas.width,canvas.height);gl.drawArrays(gl.TRIANGLES,0,6);canvas.style.visibility='visible'}catch{canvas.style.visibility='hidden'}},dispose(){gl.getExtension('WEBGL_lose_context')?.loseContext()}};
   canvas.style.visibility='hidden';media.after(canvas);record.wave.draw(record.time);
  }catch{gl.getExtension('WEBGL_lose_context')?.loseContext()}
 }
 function atmosphere(record){const c=record.cfg,a=record.amount,box=document.createElement('div');box.className='motion-atmosphere';box.dataset.motionRuntime='';record.layer.append(box);
  if(c.texture){const grain=document.createElement('div');grain.className='motion-grain';grain.style.opacity=c.texture/100*a*.24;box.append(grain)}
  if(c.dof)for(let i=0;i<3;i++){const spot=document.createElement('i');spot.className='motion-dof';spot.style.cssText=`left:${[8,66,39][i]}%;top:${[72,60,85][i]}%;width:${[260,190,330][i]}px;height:${[260,190,330][i]}px;opacity:${c.dof/100*a*.32}`;box.append(spot);animate(record,spot,[{transform:'translate3d(-20px,8px,0) scale(.94)'},{transform:'translate3d(35px,-20px,0) scale(1.08)'}],22+i*6)}
  if(c.dust)for(let i=0;i<12;i++){const dot=document.createElement('i');dot.className='motion-dust';const size=[5,10,7,15][i%4];dot.style.cssText=`left:${(i*37+11)%100}%;top:${(i*23+17)%100}%;width:${size}px;height:${size}px;opacity:${c.dust/100*a*(i%3===0?.6:.3)}`;box.append(dot);animate(record,dot,[{transform:'translate3d(-12px,25px,0)'},{transform:`translate3d(${14+i*2}px,-36px,0)`}],17+i*1.7)}
 }
 function dispose(r){clearTimeout(leaving.get(r.layer));leaving.delete(r.layer);r.animations.forEach(a=>a.cancel());r.wave?.dispose();r.layer.querySelectorAll('[data-motion-runtime]').forEach(e=>e.remove());r.media.style.filter=''}
 function refresh(){const layers=[...root().querySelectorAll(':scope>section .motion-layer,:scope>section .studio-background')].filter(l=>l.style.display!=='none'&&l.querySelector(':scope>img,:scope>video'));
  for(const[layer,r]of scenes)if(!layers.includes(layer)){dispose(r);scenes.delete(layer)}
  layers.forEach((layer,i)=>{const media=layer.querySelector(':scope>img,:scope>video'),cfg=VibeMotionSettings.normalize({...VibeMotionSettings.defaults(layer.closest('section')),...JSON.parse(layer.dataset.motionSettings||'{}')}),key=JSON.stringify(cfg),old=scenes.get(layer);if(old?.key===key&&old.media===media)return;const time=old?.time??3;let r;if(old?.media===media){r=old;r.animations.forEach(a=>a.cancel());r.animations=[];r.layer.querySelectorAll('.motion-atmosphere').forEach(e=>e.remove());r.media.style.filter='';Object.assign(r.cfg,cfg);r.key=key;r.amount=cfg.motion?cfg.strength/100:0;if(r.wave&&(!cfg.waves||!r.amount)){r.wave.dispose();r.wave.canvas.remove();r.wave=null}}else{old&&dispose(old);r={layer,media,cfg,key,time,amount:cfg.motion?cfg.strength/100:0,animations:[]}}scenes.set(layer,r);if(r.amount){camera(r,media,i);waveSurface(r);if(r.wave)camera(r,r.wave.canvas,i);atmosphere(r);if(cfg.jiggle){const j=cfg.jiggle/100*r.amount,frames=Array.from({length:41},(_,n)=>{const t=n/40*Math.PI*2,x=Math.sin(t*3)*.64+Math.sin(t*7+.7)*.23+Math.sin(t*11)*.13,y=Math.cos(t*2+.4)*.68+Math.sin(t*5)*.32,angle=Math.sin(t*4+.5)*.65+Math.sin(t*9)*.35;return{transform:`translate3d(${x*j*17}px,${y*j*11}px,0) rotate(${angle*j*.7}deg) scale(${1+.035*j})`}});const a=animate(r,layer,frames,24);a.effect.updateTiming({direction:'normal',easing:'linear'});a.effect.setKeyframes(frames.map(f=>({...f,easing:'ease-in-out'})))}}
  });sync()
 }
 function tick(now){raf=0;const dt=last?Math.min(.1,(now-last)/1000):0;last=now;for(const r of scenes.values())if(active(r.layer)){r.time+=dt*r.cfg.speed;r.wave?.draw(r.time)}if([...scenes.values()].some(r=>active(r.layer)))raf=requestAnimationFrame(tick)}
 function sync(){const present=root().querySelector(':scope>section.present');for(const r of scenes.values()){const section=r.layer.closest('section');if(section&&section!==present&&r.playing&&running()&&!leaving.has(r.layer))leaving.set(r.layer,setTimeout(()=>{leaving.delete(r.layer);r.playing=false;sync()},fadeMs(section)+150));if(section===present&&leaving.has(r.layer)){clearTimeout(leaving.get(r.layer));leaving.delete(r.layer)}const play=active(r.layer);r.playing=play;r.animations.forEach(a=>{if(play)a.play();else{const t=a.currentTime;a.pause();a.currentTime=t}});r.wave?.draw(r.time)}prefetch();root().querySelectorAll(':scope>section video').forEach(v=>{v.muted=true;const r=scenes.get(v.closest('.studio-background,.motion-layer'));v.playbackRate=r?.cfg.speed||1;if(active(v))v.play().catch(()=>{});else v.pause()});if(!raf&&[...scenes.values()].some(r=>active(r.layer))){last=0;raf=requestAnimationFrame(tick)}document.querySelector('#background-preview-motion')?.setAttribute('aria-pressed',String(preview))}
 window.DeckMotion={toggle(){preview=false;paused=!paused;sync();return paused},isPaused:()=>paused,setPaused(v){paused=v;sync()},setPreview(v){preview=!!v;sync();return preview},isPreviewing:()=>preview,sync,refresh,
  ready(){return [...scenes.values()].every(r=>r.media.tagName==='VIDEO'?r.media.readyState>=2:r.media.complete&&r.media.naturalWidth>0)},
  render(t){if(raf)cancelAnimationFrame(raf);raf=0;for(const r of scenes.values()){r.time=t*r.cfg.speed;r.animations.forEach(a=>{a.pause();a.currentTime=t*1000});r.wave?.draw(r.time)}}};
 document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',e=>{preview=false;paused=e.matches;sync()});refresh();
});
